# Copyright (c) 2016-present Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# pyright: strict
"""Type stubs for the `kth_native` CPython extension.

The hand-written sections cover:

* the eight Python-visible types exposed by the C extension
  (`Settings`, `BlockchainSettings`, `DatabaseSettings`,
  `NetworkSettings`, `NodeSettings`, `Authority`, `Endpoint`,
  `Checkpoint`), with every member that ships in the modern C-API; and

* the small set of "front-door" functions that downstream consumers
  (most notably `py-api`) actually call by hand: `node_*`, `config_*`,
  `wallet_payment_address_*`, the per-network helpers, and the chain
  fetch entry points.

Everything else (most of the 169 `chain_*` helpers — block / header /
transaction / input / output / script / merkle / history / stealth
plumbing) is enumerated below as `(*args, **kwargs) -> Any` so that
IDE name-completion and "is this exported?" checks still work, while
keeping this file maintainable. Type those in a follow-up pass when a
specific call site needs strict signatures.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Final

# ─────────────────────────────────────────────────────────────────────
# Enums (modeled as Final ints — the C-API doesn't ship Python enums)
# ─────────────────────────────────────────────────────────────────────

# kth_network_t — values must match the kth-c-api primitives.h enum.
NETWORK_MAINNET: Final[int] = 0
NETWORK_TESTNET: Final[int] = 1
NETWORK_REGTEST: Final[int] = 2
NETWORK_TESTNET4: Final[int] = 3
NETWORK_SCALENET: Final[int] = 4
NETWORK_CHIPNET: Final[int] = 5

# kth_db_mode_t
DB_MODE_PRUNED: Final[int] = 0
DB_MODE_NORMAL: Final[int] = 1
DB_MODE_FULL_INDEXED: Final[int] = 2

# StartModules — values for the second arg of node_init_run_and_wait_for_signal.
START_MODULES_JUST_CHAIN: Final[int] = 1
START_MODULES_FULL: Final[int] = 2

# ─────────────────────────────────────────────────────────────────────
# Settings types
# ─────────────────────────────────────────────────────────────────────

class NodeSettings:
    """Mirror of `kth_node_settings`."""

    sync_peers: int
    sync_timeout_seconds: int
    block_latency_seconds: int
    refresh_transactions: bool
    compact_blocks_high_bandwidth: bool
    ds_proofs_enabled: bool

    def __init__(self) -> None: ...


class DatabaseSettings:
    """Mirror of `kth_database_settings`."""

    directory: str
    db_mode: int  # one of DB_MODE_*
    reorg_pool_limit: int
    db_max_size: int
    safe_mode: bool
    cache_capacity: int

    def __init__(self) -> None: ...


class Checkpoint:
    """Mirror of `kth_checkpoint`."""

    hash: bytes  # 32 bytes, big-endian (display order)
    height: int

    def __init__(self) -> None: ...


class Authority:
    """Mirror of `kth_authority` — host:port pair."""

    ip: str
    port: int

    def __init__(self) -> None: ...


class Endpoint:
    """Mirror of `kth_endpoint` — scheme://host:port triple."""

    scheme: str
    host: str
    port: int

    def __init__(self) -> None: ...


class BlockchainSettings:
    """Mirror of `kth_blockchain_settings`. BCH-specific fields are
    only meaningful when the build was compiled with `KTH_CURRENCY_BCH`."""

    cores: int
    priority: bool
    byte_fee_satoshis: float
    sigop_fee_satoshis: float
    minimum_output_satoshis: int
    notify_limit_hours: int
    reorganization_limit: int
    checkpoints: list[Checkpoint]
    fix_checkpoints: bool
    allow_collisions: bool
    easy_blocks: bool
    retarget: bool

    # BIPs (consensus toggles).
    bip16: bool
    bip30: bool
    bip34: bool
    bip66: bool
    bip65: bool
    bip90: bool
    bip68: bool
    bip112: bool
    bip113: bool

    # BCH hard-forks (already activated on every shipped network).
    bch_uahf: bool
    bch_daa_cw144: bool
    bch_pythagoras: bool
    bch_euclid: bool
    bch_pisano: bool
    bch_mersenne: bool
    bch_fermat: bool
    bch_euler: bool
    bch_gauss: bool
    bch_descartes: bool
    bch_lobachevski: bool
    bch_galois: bool

    # Future hard-forks: timestamps only, the bool flags will be added
    # in a later kth release.
    leibniz_activation_time: int  # 2026-May
    cantor_activation_time: int   # 2027-May

    asert_half_life: int

    def __init__(self) -> None: ...


class NetworkSettings:
    """Mirror of `kth_network_settings`."""

    threads: int
    protocol_maximum: int
    protocol_minimum: int
    services: int
    invalid_services: int
    relay_transactions: bool
    validate_checksum: bool
    identifier: int
    inbound_port: int
    inbound_connections: int
    outbound_connections: int
    manual_attempt_limit: int
    connect_batch_size: int
    connect_timeout_seconds: int
    channel_handshake_seconds: int
    channel_heartbeat_minutes: int
    channel_inactivity_minutes: int
    channel_expiration_minutes: int
    channel_germination_seconds: int
    host_pool_capacity: int
    hosts_file: str
    self: Authority
    blacklist: list[Authority]
    peers: list[Endpoint]
    seeds: list[Endpoint]
    debug_file: str
    error_file: str
    archive_directory: str
    rotation_size: int
    minimum_free_space: int
    maximum_archive_size: int
    maximum_archive_files: int
    statistics_server: Authority
    verbose: bool
    use_ipv6: bool
    user_agent_blacklist: list[str]

    def __init__(self) -> None: ...


class Settings:
    """Mirror of `kth_settings` — the top-level config bundle."""

    node: NodeSettings
    chain: BlockchainSettings
    database: DatabaseSettings
    network: NetworkSettings

    def __init__(self) -> None: ...


# ─────────────────────────────────────────────────────────────────────
# Opaque handles (returned by C, passed back into C — they're
# PyCapsule objects under the hood, but Python sees them as `object`)
# ─────────────────────────────────────────────────────────────────────

# Type aliases for documentation only — they all resolve to `object` so
# the type-checker doesn't reject passing them around.
Node = object
Chain = object
P2P = object
Block = object
# `Header` is defined as a real class in the AUTO-GENERATED STUBS block below.
ChainState = object
Transaction = object
Input = object
Output = object
Script = object
Operation = object
PaymentAddress = object
OutputPoint = object
Hash = bytes  # always 32 bytes


# ─────────────────────────────────────────────────────────────────────
# Front-door API: config + node lifecycle
# ─────────────────────────────────────────────────────────────────────

def config_settings_default(network: int) -> Settings: ...
def config_node_settings_default(network: int) -> NodeSettings: ...
def config_database_settings_default(network: int) -> DatabaseSettings: ...
def config_network_settings_default(network: int) -> NetworkSettings: ...
def config_blockchain_settings_default(network: int) -> BlockchainSettings: ...
def config_settings_get_from_file(
    path: str,
) -> tuple[int, Settings | None, str | None]:
    """Load settings from a config file.

    Returns a 3-tuple `(ok, settings, error)`:
      * on success: `(1, settings, None)`
      * on failure: `(0, None, error_message)`
    """
    ...

def node_construct(settings: Settings, stdout_console: bool, /) -> Node: ...
def node_destruct(node: Node, /) -> None: ...
def node_chain(node: Node, /) -> Chain: ...
def node_p2p(node: Node, /) -> P2P: ...
def node_signal_stop(node: Node, /) -> None: ...
def node_print_thread_id() -> None: ...
def node_init_run_and_wait_for_signal(
    node: Node,
    start_modules: int,
    callback: Callable[[int], Any],
    /,
) -> None: ...

def p2p_address_count(p2p: P2P, /) -> int: ...
def p2p_close(p2p: P2P, /) -> None: ...
def p2p_stop(p2p: P2P, /) -> None: ...
def p2p_stopped(p2p: P2P, /) -> bool: ...


# ─────────────────────────────────────────────────────────────────────
# Wallet — payment address triple
# ─────────────────────────────────────────────────────────────────────

def wallet_payment_address_construct_from_string(addr: str, /) -> PaymentAddress: ...
def wallet_payment_address_destruct(addr: PaymentAddress, /) -> None: ...
def wallet_payment_address_version(addr: PaymentAddress, /) -> int: ...
def wallet_payment_address_encoded_legacy(addr: PaymentAddress, /) -> str: ...

# NOTE: the `_cashaddr` and `_token` variants are only compiled in when
# the C extension was built with `KTH_CURRENCY=BCH` (the default). On
# BTC/LTC builds these functions are absent at runtime; calling them
# raises `AttributeError`. Until py-native ships per-currency stubs we
# expose them unconditionally — guard call sites with a feature check
# (`hasattr(kth_native, "wallet_payment_address_encoded_cashaddr")`)
# in code that needs to work across currencies.
def wallet_payment_address_encoded_cashaddr(
    addr: PaymentAddress, token_aware: bool, /
) -> str: ...
def wallet_payment_address_encoded_token(addr: PaymentAddress, /) -> str: ...


# ─────────────────────────────────────────────────────────────────────
# A handful of typed `chain_*` entry points commonly called by hand.
# ─────────────────────────────────────────────────────────────────────

def chain_fetch_last_height(
    chain: Chain, callback: Callable[[int, int], Any], /
) -> None: ...
def chain_fetch_block_by_height(
    chain: Chain, height: int, callback: Callable[[int, Block, int], Any], /
) -> None: ...
def chain_fetch_block_by_hash(
    chain: Chain, hash: Hash, callback: Callable[[int, Block, int], Any], /
) -> None: ...
def chain_fetch_block_height(
    chain: Chain, hash: Hash, callback: Callable[[int, int], Any], /
) -> None: ...
def chain_fetch_transaction(
    chain: Chain,
    hash: Hash,
    require_confirmed: bool,
    callback: Callable[[int, Transaction, int, int], Any],
    /,
) -> None: ...

def chain_block_destruct(block: Block, /) -> None: ...
def chain_block_hash(block: Block, /) -> Hash: ...
def chain_block_header(block: Block, /) -> Header: ...
def chain_block_transactions(block: Block, /) -> object: ...
def chain_block_serialized_size(block: Block, /) -> int: ...
def chain_block_factory_from_data(data: bytes, /) -> Block: ...

def chain_transaction_destruct(tx: Transaction, /) -> None: ...
def chain_transaction_hash(tx: Transaction, /) -> bytearray: ...
def chain_transaction_locktime(tx: Transaction, /) -> int: ...
def chain_transaction_factory_from_data(data: bytes, /) -> Transaction: ...

# chain_header / chain_script / chain_output_point / chain_point stubs are
# auto-generated below the AUTO-GENERATED block once each class is migrated.


# ─────────────────────────────────────────────────────────────────────
# All remaining `chain_*` helpers — left as untyped catch-alls. Promote
# to a real signature above when a caller actually needs strict types.
# ─────────────────────────────────────────────────────────────────────

def chain_block_claim(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_fees(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_generate_merkle_root(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_distinct_transaction_set(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_extra_coinbases(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_internal_double_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_coinbase_claim(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_coinbase_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_merkle_root(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_reward(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_signature_operations_bip16_active(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_total_inputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_header(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_nonce(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_reset(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_transaction_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_transaction_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_block_header_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_block_header_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_compact_block_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_compact_block_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_history(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_merkle_block_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_merkle_block_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_transaction_position(*args: Any, **kwargs: Any) -> Any: ...
# chain_header stubs are auto-generated (see AUTO-GENERATED block).
def chain_history_compact_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_point(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_point_kind(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_value_or_previous_checksum(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_factory_from_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_previous_output(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_sequence(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_hash_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_header(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_reset(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_total_transaction_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_organize_block(*args: Any, **kwargs: Any) -> Any: ...
def chain_organize_transaction(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_factory_from_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_ephemeral_public_key_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_public_key_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_transaction_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_subscribe_blockchain(*args: Any, **kwargs: Any) -> Any: ...
def chain_subscribe_transaction(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_fees(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_inputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_double_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_locktime_conflict(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_mature(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_missing_previous_outputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_null_non_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_oversized_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_overspent(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_outputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_set_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_signature_operations_bip16_active(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_total_input_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_total_output_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_unsubscribe(*args: Any, **kwargs: Any) -> Any: ...
def chain_validate_tx(*args: Any, **kwargs: Any) -> Any: ...


# ── AUTO-GENERATED STUBS START ──────────────────────────────────────
# ─── Block (auto-generated, do not edit) ─────────────────────────

class Block:
    """Opaque handle to a `kth::domain::chain::block`. Constructed by
    `chain_block_construct_*` and released by
    `chain_block_destruct`."""
    ...

def chain_block_construct_default() -> Block: ...
def chain_block_construct_from_data(reader: bytes, wire: bool) -> Block: ...
def chain_block_construct(header: "Header", transactions: object) -> Block: ...
def chain_block_copy(self: Block) -> Block: ...
def chain_block_destruct(self: Block) -> None: ...
def chain_block_to_data_simple(self: Block) -> bytes: ...
def chain_block_serialized_size(self: Block) -> int: ...
def chain_block_set_transactions(self: Block, value: object) -> None: ...
def chain_block_genesis_mainnet() -> "Block" | None: ...
def chain_block_genesis_testnet() -> "Block" | None: ...
def chain_block_genesis_regtest() -> "Block" | None: ...
def chain_block_genesis_testnet4() -> "Block" | None: ...
def chain_block_genesis_scalenet() -> "Block" | None: ...
def chain_block_genesis_chipnet() -> "Block" | None: ...
def chain_block_locator_size(top: int) -> int: ...
def chain_block_locator_heights(top: int) -> object | None: ...
def chain_block_signature_operations_simple(self: Block) -> int: ...
def chain_block_total_inputs(self: Block, with_coinbase: bool) -> int: ...
def chain_block_check(self: Block) -> int: ...
def chain_block_accept(self: Block, flags: int, height: int, median_time_past: int, max_block_size_dynamic: int, max_sigops: int, is_under_checkpoint: bool, transactions: bool) -> int: ...
def chain_block_connect(self: Block) -> int: ...
def chain_block_equals(self: Block, other: Block) -> bool: ...
def chain_block_is_valid(self: Block) -> bool: ...
def chain_block_to_data(self: Block, serialized_size: int) -> bytes: ...
def chain_block_to_hashes(self: Block) -> object | None: ...
def chain_block_header(self: Block) -> "Header" | None: ...
def chain_block_set_header(self: Block, value: "Header") -> None: ...
def chain_block_transactions(self: Block) -> "TransactionList" | None: ...
def chain_block_hash(self: Block) -> bytes: ...
def chain_block_subsidy(height: int, retarget: bool) -> int: ...
def chain_block_fees(self: Block) -> int: ...
def chain_block_claim(self: Block) -> int: ...
def chain_block_reward(self: Block, height: int) -> int: ...
def chain_block_generate_merkle_root(self: Block) -> bytes: ...
def chain_block_signature_operations(self: Block, bip16: bool, bip141: bool) -> int: ...
def chain_block_is_extra_coinbases(self: Block) -> bool: ...
def chain_block_is_final(self: Block, height: int, block_time: int) -> bool: ...
def chain_block_is_distinct_transaction_set(self: Block) -> bool: ...
def chain_block_is_valid_coinbase_claim(self: Block, height: int) -> bool: ...
def chain_block_is_valid_coinbase_script(self: Block, height: int) -> bool: ...
def chain_block_is_forward_reference(self: Block) -> bool: ...
def chain_block_is_canonical_ordered(self: Block) -> bool: ...
def chain_block_is_internal_double_spend(self: Block) -> bool: ...
def chain_block_is_valid_merkle_root(self: Block) -> bool: ...
def chain_block_check_transactions(self: Block) -> int: ...
def chain_block_accept_transactions(self: Block, flags: int, height: int, median_time_past: int, max_sigops: int, is_under_checkpoint: bool) -> int: ...
def chain_block_connect_transactions(self: Block, state: "ChainState") -> int: ...
def chain_block_reset(self: Block) -> None: ...
def chain_block_non_coinbase_input_count(self: Block) -> int: ...

# ─── BlockList (auto-generated, do not edit) ─────────────────────────

class BlockList:
    """Opaque handle to a `std::vector<kth::domain::chain::block>`."""
    ...

def chain_block_list_construct_default() -> BlockList: ...
def chain_block_list_push_back(list: BlockList, elem: Block) -> None: ...
def chain_block_list_destruct(list: BlockList) -> None: ...
def chain_block_list_count(list: BlockList) -> int: ...
def chain_block_list_nth(list: BlockList, index: int) -> Block: ...
def chain_block_list_assign_at(list: BlockList, index: int, elem: Block) -> None: ...
def chain_block_list_erase(list: BlockList, index: int) -> None: ...

# ─── Header (auto-generated, do not edit) ─────────────────────────

class Header:
    """Opaque handle to a `kth::domain::chain::header`. Constructed by
    `chain_header_construct_*` and released by
    `chain_header_destruct`."""
    ...

def chain_header_construct_default() -> Header: ...
def chain_header_construct_from_data(reader: bytes, wire: bool) -> Header: ...
def chain_header_construct(version: int, previous_block_hash: bytes, merkle: bytes, timestamp: int, bits: int, nonce: int) -> Header: ...
def chain_header_copy(self: Header) -> Header: ...
def chain_header_destruct(self: Header) -> None: ...
def chain_header_to_data(self: Header, wire: bool) -> bytes: ...
def chain_header_serialized_size(self: Header, wire: bool) -> int: ...
def chain_header_set_version(self: Header, value: int) -> None: ...
def chain_header_set_previous_block_hash(self: Header, value: bytes) -> None: ...
def chain_header_set_merkle(self: Header, value: bytes) -> None: ...
def chain_header_set_timestamp(self: Header, value: int) -> None: ...
def chain_header_set_bits(self: Header, value: int) -> None: ...
def chain_header_set_nonce(self: Header, value: int) -> None: ...
def chain_header_hash_pow(self: Header) -> bytes: ...
def chain_header_is_valid_proof_of_work(self: Header, retarget: bool) -> bool: ...
def chain_header_check(self: Header, retarget: bool) -> int: ...
def chain_header_accept(self: Header, state: "ChainState") -> int: ...
def chain_header_reset(self: Header) -> None: ...
def chain_header_equals(self: Header, other: Header) -> bool: ...
def chain_header_is_valid(self: Header) -> bool: ...
def chain_header_satoshi_fixed_size() -> int: ...
def chain_header_version(self: Header) -> int: ...
def chain_header_previous_block_hash(self: Header) -> bytes: ...
def chain_header_merkle(self: Header) -> bytes: ...
def chain_header_timestamp(self: Header) -> int: ...
def chain_header_bits(self: Header) -> int: ...
def chain_header_nonce(self: Header) -> int: ...
def chain_header_is_valid_timestamp(self: Header) -> bool: ...

# ─── Point (auto-generated, do not edit) ─────────────────────────

class Point:
    """Opaque handle to a `kth::domain::chain::point`. Constructed by
    `chain_point_construct_*` and released by
    `chain_point_destruct`."""
    ...

def chain_point_construct_default() -> Point: ...
def chain_point_construct_from_data(reader: bytes, wire: bool) -> Point: ...
def chain_point_construct(hash: bytes, index: int) -> Point: ...
def chain_point_copy(self: Point) -> Point: ...
def chain_point_destruct(self: Point) -> None: ...
def chain_point_equals(self: Point, other: Point) -> bool: ...
def chain_point_null() -> "Point" | None: ...
def chain_point_is_valid(self: Point) -> bool: ...
def chain_point_to_data(self: Point, wire: bool) -> bytes: ...
def chain_point_satoshi_fixed_size() -> int: ...
def chain_point_serialized_size(self: Point, wire: bool) -> int: ...
def chain_point_hash(self: Point) -> bytes: ...
def chain_point_set_hash(self: Point, value: bytes) -> None: ...
def chain_point_index(self: Point) -> int: ...
def chain_point_set_index(self: Point, value: int) -> None: ...
def chain_point_checksum(self: Point) -> int: ...
def chain_point_is_null(self: Point) -> bool: ...
def chain_point_reset(self: Point) -> None: ...

# ─── PointList (auto-generated, do not edit) ─────────────────────────

class PointList:
    """Opaque handle to a `std::vector<kth::domain::chain::point>`."""
    ...

def chain_point_list_construct_default() -> PointList: ...
def chain_point_list_push_back(list: PointList, elem: Point) -> None: ...
def chain_point_list_destruct(list: PointList) -> None: ...
def chain_point_list_count(list: PointList) -> int: ...
def chain_point_list_nth(list: PointList, index: int) -> Point: ...
def chain_point_list_assign_at(list: PointList, index: int, elem: Point) -> None: ...
def chain_point_list_erase(list: PointList, index: int) -> None: ...

# ─── OutputPoint (auto-generated, do not edit) ─────────────────────────

class OutputPoint:
    """Opaque handle to a `kth::domain::chain::output_point`. Constructed by
    `chain_output_point_construct_*` and released by
    `chain_output_point_destruct`."""
    ...

def chain_output_point_construct_default() -> OutputPoint: ...
def chain_output_point_construct_from_data(reader: bytes, wire: bool) -> OutputPoint: ...
def chain_output_point_construct_from_hash_index(hash: bytes, index: int) -> OutputPoint: ...
def chain_output_point_construct_from_point(x: "Point") -> OutputPoint: ...
def chain_output_point_copy(self: OutputPoint) -> OutputPoint: ...
def chain_output_point_destruct(self: OutputPoint) -> None: ...
def chain_output_point_equals(self: OutputPoint, other: OutputPoint) -> bool: ...
def chain_output_point_is_mature(self: OutputPoint, height: int) -> bool: ...
def chain_output_point_is_valid(self: OutputPoint) -> bool: ...
def chain_output_point_to_data(self: OutputPoint, wire: bool) -> bytes: ...
def chain_output_point_satoshi_fixed_size() -> int: ...
def chain_output_point_serialized_size(self: OutputPoint, wire: bool) -> int: ...
def chain_output_point_hash(self: OutputPoint) -> bytes: ...
def chain_output_point_set_hash(self: OutputPoint, value: bytes) -> None: ...
def chain_output_point_index(self: OutputPoint) -> int: ...
def chain_output_point_set_index(self: OutputPoint, value: int) -> None: ...
def chain_output_point_checksum(self: OutputPoint) -> int: ...
def chain_output_point_is_null(self: OutputPoint) -> bool: ...
def chain_output_point_reset(self: OutputPoint) -> None: ...

# ─── OutputPointList (auto-generated, do not edit) ─────────────────────────

class OutputPointList:
    """Opaque handle to a `std::vector<kth::domain::chain::output_point>`."""
    ...

def chain_output_point_list_construct_default() -> OutputPointList: ...
def chain_output_point_list_push_back(list: OutputPointList, elem: OutputPoint) -> None: ...
def chain_output_point_list_destruct(list: OutputPointList) -> None: ...
def chain_output_point_list_count(list: OutputPointList) -> int: ...
def chain_output_point_list_nth(list: OutputPointList, index: int) -> OutputPoint: ...
def chain_output_point_list_assign_at(list: OutputPointList, index: int, elem: OutputPoint) -> None: ...
def chain_output_point_list_erase(list: OutputPointList, index: int) -> None: ...

# ─── Script (auto-generated, do not edit) ─────────────────────────

class Script:
    """Opaque handle to a `kth::domain::chain::script`. Constructed by
    `chain_script_construct_*` and released by
    `chain_script_destruct`."""
    ...

def chain_script_construct_default() -> Script: ...
def chain_script_construct_from_data(reader: bytes, wire: bool) -> Script: ...
def chain_script_construct_from_operations(ops: object) -> Script: ...
def chain_script_construct_from_encoded_prefix(encoded: bytes, prefix: bool) -> Script: ...
def chain_script_copy(self: Script) -> Script: ...
def chain_script_destruct(self: Script) -> None: ...
def chain_script_from_data_with_size(reader: bytes, size: int) -> "Script": ...
def chain_script_from_operations(self: Script, ops: object) -> None: ...
def chain_script_from_string(self: Script, mnemonic: str) -> bool: ...
def chain_script_is_valid_operations(self: Script) -> bool: ...
def chain_script_to_string(self: Script, active_flags: int) -> str | None: ...
def chain_script_clear(self: Script) -> None: ...
def chain_script_empty(self: Script) -> bool: ...
def chain_script_size(self: Script) -> int: ...
def chain_script_front(self: Script) -> "Operation" | None: ...
def chain_script_back(self: Script) -> "Operation" | None: ...
def chain_script_at(self: Script, index: int) -> "Operation" | None: ...
def chain_script_operations(self: Script) -> "OperationList" | None: ...
def chain_script_first_operation(self: Script) -> "Operation" | None: ...
def chain_script_create_endorsement(secret: bytes, prevout_script: "Script", tx: "Transaction", input_index: int, sighash_type: int, active_flags: int, value: int, type: int) -> bytes: ...
def chain_script_is_push_only(ops: object) -> bool: ...
def chain_script_is_relaxed_push(ops: object) -> bool: ...
def chain_script_is_coinbase_pattern(ops: object, height: int) -> bool: ...
def chain_script_is_null_data_pattern(ops: object) -> bool: ...
def chain_script_is_pay_multisig_pattern(ops: object) -> bool: ...
def chain_script_is_pay_public_key_pattern(ops: object) -> bool: ...
def chain_script_is_pay_public_key_hash_pattern(ops: object) -> bool: ...
def chain_script_is_pay_script_hash_pattern(ops: object) -> bool: ...
def chain_script_is_pay_script_hash_32_pattern(ops: object) -> bool: ...
def chain_script_is_sign_multisig_pattern(ops: object) -> bool: ...
def chain_script_is_sign_public_key_pattern(ops: object) -> bool: ...
def chain_script_is_sign_public_key_hash_pattern(ops: object) -> bool: ...
def chain_script_is_sign_script_hash_pattern(ops: object) -> bool: ...
def chain_script_to_null_data_pattern(data: bytes) -> "OperationList" | None: ...
def chain_script_to_pay_public_key_pattern(point: bytes) -> "OperationList" | None: ...
def chain_script_to_pay_public_key_hash_pattern(hash: bytes) -> "OperationList" | None: ...
def chain_script_to_pay_public_key_hash_pattern_unlocking(end: bytes, pubkey: "EcPublic") -> "OperationList" | None: ...
def chain_script_to_pay_public_key_hash_pattern_unlocking_placeholder(endorsement_size: int, pubkey_size: int) -> "OperationList" | None: ...
def chain_script_to_pay_script_hash_pattern_unlocking_placeholder(script_size: int, multisig: bool) -> "OperationList" | None: ...
def chain_script_to_pay_script_hash_pattern(hash: bytes) -> "OperationList" | None: ...
def chain_script_to_pay_script_hash_32_pattern(hash: bytes) -> "OperationList" | None: ...
def chain_script_to_pay_multisig_pattern_ec_compressed_list(signatures: int, points: object) -> "OperationList" | None: ...
def chain_script_to_pay_multisig_pattern_data_stack(signatures: int, points: object) -> "OperationList" | None: ...
def chain_script_pattern(self: Script) -> int: ...
def chain_script_output_pattern_simple(self: Script) -> int: ...
def chain_script_output_pattern(self: Script, flags: int) -> int: ...
def chain_script_input_pattern(self: Script) -> int: ...
def chain_script_sigops(self: Script, accurate: bool) -> int: ...
def chain_script_is_unspendable(self: Script) -> bool: ...
def chain_script_reset(self: Script) -> None: ...
def chain_script_is_pay_to_script_hash(self: Script, flags: int) -> bool: ...
def chain_script_is_pay_to_script_hash_32(self: Script, flags: int) -> bool: ...
def chain_script_verify(tx: "Transaction", input_index: int, flags: int, input_script: "Script", prevout_script: "Script", value: int) -> int: ...
def chain_script_verify_simple(tx: "Transaction", input: int, flags: int) -> int: ...
def chain_script_equals(self: Script, other: Script) -> bool: ...
def chain_script_is_valid(self: Script) -> bool: ...
def chain_script_to_data(self: Script, prefix: bool) -> bytes: ...
def chain_script_serialized_size(self: Script, prefix: bool) -> int: ...
def chain_script_bytes(self: Script) -> bytes: ...
def chain_script_is_enabled(active_flags: int, fork: int) -> bool: ...

# ─── Output (auto-generated, do not edit) ─────────────────────────

class Output:
    """Opaque handle to a `kth::domain::chain::output`. Constructed by
    `chain_output_construct_*` and released by
    `chain_output_destruct`."""
    ...

def chain_output_construct_default() -> Output: ...
def chain_output_construct_from_data(reader: bytes, wire: bool) -> Output: ...
def chain_output_copy(self: Output) -> Output: ...
def chain_output_destruct(self: Output) -> None: ...
def chain_output_to_data(self: Output, wire: bool) -> bytes: ...
def chain_output_serialized_size(self: Output, wire: bool) -> int: ...
def chain_output_set_script(self: Output, value: "Script") -> None: ...
def chain_output_address_simple(self: Output, testnet: bool) -> "PaymentAddress" | None: ...
def chain_output_address(self: Output, p2kh_version: int, p2sh_version: int) -> "PaymentAddress" | None: ...
def chain_output_addresses(self: Output, p2kh_version: int, p2sh_version: int) -> "PaymentAddressList" | None: ...
def chain_output_equals(self: Output, other: Output) -> bool: ...
def chain_output_is_valid(self: Output) -> bool: ...
def chain_output_value(self: Output) -> int: ...
def chain_output_set_value(self: Output, value: int) -> None: ...
def chain_output_script(self: Output) -> "Script" | None: ...
def chain_output_signature_operations(self: Output, bip141: bool) -> int: ...
def chain_output_is_dust(self: Output, minimum_output_value: int) -> bool: ...
def chain_output_reset(self: Output) -> None: ...

# ─── OutputList (auto-generated, do not edit) ─────────────────────────

class OutputList:
    """Opaque handle to a `std::vector<kth::domain::chain::output>`."""
    ...

def chain_output_list_construct_default() -> OutputList: ...
def chain_output_list_push_back(list: OutputList, elem: Output) -> None: ...
def chain_output_list_destruct(list: OutputList) -> None: ...
def chain_output_list_count(list: OutputList) -> int: ...
def chain_output_list_nth(list: OutputList, index: int) -> Output: ...
def chain_output_list_assign_at(list: OutputList, index: int, elem: Output) -> None: ...
def chain_output_list_erase(list: OutputList, index: int) -> None: ...

# ─── Input (auto-generated, do not edit) ─────────────────────────

class Input:
    """Opaque handle to a `kth::domain::chain::input`. Constructed by
    `chain_input_construct_*` and released by
    `chain_input_destruct`."""
    ...

def chain_input_construct_default() -> Input: ...
def chain_input_construct_from_data(reader: bytes, wire: bool) -> Input: ...
def chain_input_construct(previous_output: "OutputPoint", script: "Script", sequence: int) -> Input: ...
def chain_input_copy(self: Input) -> Input: ...
def chain_input_destruct(self: Input) -> None: ...
def chain_input_set_script(self: Input, value: "Script") -> None: ...
def chain_input_address(self: Input) -> "PaymentAddress" | None: ...
def chain_input_addresses(self: Input) -> "PaymentAddressList" | None: ...
def chain_input_reset(self: Input) -> None: ...
def chain_input_equals(self: Input, other: Input) -> bool: ...
def chain_input_is_valid(self: Input) -> bool: ...
def chain_input_to_data(self: Input, wire: bool) -> bytes: ...
def chain_input_serialized_size(self: Input, wire: bool) -> int: ...
def chain_input_previous_output(self: Input) -> "OutputPoint" | None: ...
def chain_input_set_previous_output(self: Input, value: "OutputPoint") -> None: ...
def chain_input_script(self: Input) -> "Script" | None: ...
def chain_input_sequence(self: Input) -> int: ...
def chain_input_set_sequence(self: Input, value: int) -> None: ...
def chain_input_is_final(self: Input) -> bool: ...
def chain_input_is_locked(self: Input, block_height: int, median_time_past: int) -> bool: ...
def chain_input_signature_operations(self: Input, bip16: bool, bip141: bool) -> int: ...
def chain_input_extract_embedded_script(self: Input) -> "Script": ...

# ─── InputList (auto-generated, do not edit) ─────────────────────────

class InputList:
    """Opaque handle to a `std::vector<kth::domain::chain::input>`."""
    ...

def chain_input_list_construct_default() -> InputList: ...
def chain_input_list_push_back(list: InputList, elem: Input) -> None: ...
def chain_input_list_destruct(list: InputList) -> None: ...
def chain_input_list_count(list: InputList) -> int: ...
def chain_input_list_nth(list: InputList, index: int) -> Input: ...
def chain_input_list_assign_at(list: InputList, index: int, elem: Input) -> None: ...
def chain_input_list_erase(list: InputList, index: int) -> None: ...

# ─── Transaction (auto-generated, do not edit) ─────────────────────────

class Transaction:
    """Opaque handle to a `kth::domain::chain::transaction`. Constructed by
    `chain_transaction_construct_*` and released by
    `chain_transaction_destruct`."""
    ...

def chain_transaction_construct_default() -> Transaction: ...
def chain_transaction_construct_from_data(reader: bytes, wire: bool) -> Transaction: ...
def chain_transaction_construct_from_version_locktime_inputs_outputs(version: int, locktime: int, inputs: object, outputs: object) -> Transaction: ...
def chain_transaction_construct_from_transaction_hash(x: "Transaction", hash: bytes) -> Transaction: ...
def chain_transaction_copy(self: Transaction) -> Transaction: ...
def chain_transaction_destruct(self: Transaction) -> None: ...
def chain_transaction_to_data(self: Transaction, wire: bool) -> bytes: ...
def chain_transaction_serialized_size(self: Transaction, wire: bool) -> int: ...
def chain_transaction_set_version(self: Transaction, value: int) -> None: ...
def chain_transaction_set_locktime(self: Transaction, value: int) -> None: ...
def chain_transaction_set_inputs(self: Transaction, value: object) -> None: ...
def chain_transaction_set_outputs(self: Transaction, value: object) -> None: ...
def chain_transaction_outputs_hash(self: Transaction) -> bytes: ...
def chain_transaction_inpoints_hash(self: Transaction) -> bytes: ...
def chain_transaction_sequences_hash(self: Transaction) -> bytes: ...
def chain_transaction_utxos_hash(self: Transaction) -> bytes: ...
def chain_transaction_hash(self: Transaction) -> bytes: ...
def chain_transaction_recompute_hash(self: Transaction) -> None: ...
def chain_transaction_fees(self: Transaction) -> int: ...
def chain_transaction_total_input_value(self: Transaction) -> int: ...
def chain_transaction_total_output_value(self: Transaction) -> int: ...
def chain_transaction_signature_operations_simple(self: Transaction) -> int: ...
def chain_transaction_is_overspent(self: Transaction) -> bool: ...
def chain_transaction_check(self: Transaction, max_block_size: int, transaction_pool: bool, retarget: bool) -> int: ...
def chain_transaction_accept(self: Transaction, flags: int, height: int, median_time_past: int, max_sigops: int, is_under_checkpoint: bool, transaction_pool: bool) -> int: ...
def chain_transaction_connect_simple(self: Transaction) -> int: ...
def chain_transaction_connect(self: Transaction, state: "ChainState") -> int: ...
def chain_transaction_connect_input(self: Transaction, state: "ChainState", input_index: int) -> int: ...
def chain_transaction_reset(self: Transaction) -> None: ...
def chain_transaction_equals(self: Transaction, other: Transaction) -> bool: ...
def chain_transaction_is_valid(self: Transaction) -> bool: ...
def chain_transaction_version(self: Transaction) -> int: ...
def chain_transaction_locktime(self: Transaction) -> int: ...
def chain_transaction_inputs(self: Transaction) -> "InputList" | None: ...
def chain_transaction_outputs(self: Transaction) -> "OutputList" | None: ...
def chain_transaction_previous_outputs(self: Transaction) -> "PointList" | None: ...
def chain_transaction_missing_previous_outputs(self: Transaction) -> "PointList" | None: ...
def chain_transaction_missing_previous_transactions(self: Transaction) -> object | None: ...
def chain_transaction_signature_operations(self: Transaction, bip16: bool, bip141: bool) -> int: ...
def chain_transaction_is_coinbase(self: Transaction) -> bool: ...
def chain_transaction_is_null_non_coinbase(self: Transaction) -> bool: ...
def chain_transaction_is_oversized_coinbase(self: Transaction) -> bool: ...
def chain_transaction_is_mature(self: Transaction, height: int) -> bool: ...
def chain_transaction_is_internal_double_spend(self: Transaction) -> bool: ...
def chain_transaction_is_double_spend(self: Transaction, include_unconfirmed: bool) -> bool: ...
def chain_transaction_is_dusty(self: Transaction, minimum_output_value: int) -> bool: ...
def chain_transaction_is_missing_previous_outputs(self: Transaction) -> bool: ...
def chain_transaction_is_final(self: Transaction, block_height: int, block_time: int) -> bool: ...
def chain_transaction_is_locked(self: Transaction, block_height: int, median_time_past: int) -> bool: ...
def chain_transaction_is_locktime_conflict(self: Transaction) -> bool: ...
def chain_transaction_min_tx_size(self: Transaction, flags: int) -> int: ...
def chain_transaction_is_standard_simple(self: Transaction) -> bool: ...
def chain_transaction_is_standard(self: Transaction, flags: int) -> bool: ...

# ─── TransactionList (auto-generated, do not edit) ─────────────────────────

class TransactionList:
    """Opaque handle to a `std::vector<kth::domain::chain::transaction>`."""
    ...

def chain_transaction_list_construct_default() -> TransactionList: ...
def chain_transaction_list_push_back(list: TransactionList, elem: Transaction) -> None: ...
def chain_transaction_list_destruct(list: TransactionList) -> None: ...
def chain_transaction_list_count(list: TransactionList) -> int: ...
def chain_transaction_list_nth(list: TransactionList, index: int) -> Transaction: ...
def chain_transaction_list_assign_at(list: TransactionList, index: int, elem: Transaction) -> None: ...
def chain_transaction_list_erase(list: TransactionList, index: int) -> None: ...

# ─── Binary (auto-generated, do not edit) ─────────────────────────

class Binary:
    """Opaque handle to a `kth::binary`. Constructed by
    `core_binary_construct_*` and released by
    `core_binary_destruct`."""
    ...

def core_binary_construct_default() -> Binary: ...
def core_binary_construct_from_bit_string(bit_string: str) -> Binary: ...
def core_binary_construct_from_size_number(size: int, number: int) -> Binary: ...
def core_binary_construct_from_size_blocks(size: int, blocks: bytes) -> Binary: ...
def core_binary_copy(self: Binary) -> Binary: ...
def core_binary_destruct(self: Binary) -> None: ...
def core_binary_blocks_size(bit_size: int) -> int: ...
def core_binary_is_base2(text: str) -> bool: ...
def core_binary_resize(self: Binary, size: int) -> None: ...
def core_binary_at(self: Binary, index: int) -> bool: ...
def core_binary_blocks(self: Binary) -> bytes: ...
def core_binary_encoded(self: Binary) -> str | None: ...
def core_binary_size(self: Binary) -> int: ...
def core_binary_append(self: Binary, post: "Binary") -> None: ...
def core_binary_prepend(self: Binary, prior: "Binary") -> None: ...
def core_binary_shift_left(self: Binary, distance: int) -> None: ...
def core_binary_shift_right(self: Binary, distance: int) -> None: ...
def core_binary_substring(self: Binary, start: int, length: int) -> "Binary" | None: ...
def core_binary_is_prefix_of_span(self: Binary, field: bytes) -> bool: ...
def core_binary_is_prefix_of_uint32(self: Binary, field: int) -> bool: ...
def core_binary_is_prefix_of_binary(self: Binary, field: "Binary") -> bool: ...
def core_binary_equals(self: Binary, other: Binary) -> bool: ...
def core_binary_less(self: Binary, x: "Binary") -> bool: ...

# ─── GetBlocks (auto-generated, do not edit) ─────────────────────────

class GetBlocks:
    """Opaque handle to a `kth::domain::message::get_blocks`. Constructed by
    `chain_get_blocks_construct_*` and released by
    `chain_get_blocks_destruct`."""
    ...

def chain_get_blocks_construct_default() -> GetBlocks: ...
def chain_get_blocks_construct_from_data(reader: bytes, version: int) -> GetBlocks: ...
def chain_get_blocks_construct(start: object, stop: bytes) -> GetBlocks: ...
def chain_get_blocks_copy(self: GetBlocks) -> GetBlocks: ...
def chain_get_blocks_destruct(self: GetBlocks) -> None: ...
def chain_get_blocks_equals(self: GetBlocks, other: GetBlocks) -> bool: ...
def chain_get_blocks_start_hashes(self: GetBlocks) -> object | None: ...
def chain_get_blocks_set_start_hashes(self: GetBlocks, value: object) -> None: ...
def chain_get_blocks_stop_hash(self: GetBlocks) -> bytes: ...
def chain_get_blocks_set_stop_hash(self: GetBlocks, value: bytes) -> None: ...
def chain_get_blocks_to_data(self: GetBlocks, version: int) -> bytes: ...
def chain_get_blocks_is_valid(self: GetBlocks) -> bool: ...
def chain_get_blocks_reset(self: GetBlocks) -> None: ...
def chain_get_blocks_serialized_size(self: GetBlocks, version: int) -> int: ...

# ─── GetHeaders (auto-generated, do not edit) ─────────────────────────

class GetHeaders:
    """Opaque handle to a `kth::domain::message::get_headers`. Constructed by
    `chain_get_headers_construct_*` and released by
    `chain_get_headers_destruct`."""
    ...

def chain_get_headers_construct_default() -> GetHeaders: ...
def chain_get_headers_construct_from_data(reader: bytes, version: int) -> GetHeaders: ...
def chain_get_headers_construct(start: object, stop: bytes) -> GetHeaders: ...
def chain_get_headers_copy(self: GetHeaders) -> GetHeaders: ...
def chain_get_headers_destruct(self: GetHeaders) -> None: ...
def chain_get_headers_equals(self: GetHeaders, other: GetHeaders) -> bool: ...
def chain_get_headers_start_hashes(self: GetHeaders) -> object | None: ...
def chain_get_headers_set_start_hashes(self: GetHeaders, value: object) -> None: ...
def chain_get_headers_stop_hash(self: GetHeaders) -> bytes: ...
def chain_get_headers_set_stop_hash(self: GetHeaders, value: bytes) -> None: ...
def chain_get_headers_to_data(self: GetHeaders, version: int) -> bytes: ...
def chain_get_headers_is_valid(self: GetHeaders) -> bool: ...
def chain_get_headers_reset(self: GetHeaders) -> None: ...
def chain_get_headers_serialized_size(self: GetHeaders, version: int) -> int: ...

# ─── MerkleBlock (auto-generated, do not edit) ─────────────────────────

class MerkleBlock:
    """Opaque handle to a `kth::domain::message::merkle_block`. Constructed by
    `chain_merkle_block_construct_*` and released by
    `chain_merkle_block_destruct`."""
    ...

def chain_merkle_block_construct_default() -> MerkleBlock: ...
def chain_merkle_block_construct_from_data(reader: bytes, version: int) -> MerkleBlock: ...
def chain_merkle_block_construct_from_header_total_transactions_hashes_flags(header: "Header", total_transactions: int, hashes: object, flags: bytes) -> MerkleBlock: ...
def chain_merkle_block_construct_from_block(block: "Block") -> MerkleBlock: ...
def chain_merkle_block_copy(self: MerkleBlock) -> MerkleBlock: ...
def chain_merkle_block_destruct(self: MerkleBlock) -> None: ...
def chain_merkle_block_equals(self: MerkleBlock, other: MerkleBlock) -> bool: ...
def chain_merkle_block_header(self: MerkleBlock) -> "Header" | None: ...
def chain_merkle_block_set_header(self: MerkleBlock, value: "Header") -> None: ...
def chain_merkle_block_total_transactions(self: MerkleBlock) -> int: ...
def chain_merkle_block_set_total_transactions(self: MerkleBlock, value: int) -> None: ...
def chain_merkle_block_hashes(self: MerkleBlock) -> object | None: ...
def chain_merkle_block_set_hashes(self: MerkleBlock, value: object) -> None: ...
def chain_merkle_block_flags(self: MerkleBlock) -> bytes: ...
def chain_merkle_block_set_flags(self: MerkleBlock, value: bytes) -> None: ...
def chain_merkle_block_to_data(self: MerkleBlock, version: int) -> bytes: ...
def chain_merkle_block_is_valid(self: MerkleBlock) -> bool: ...
def chain_merkle_block_reset(self: MerkleBlock) -> None: ...
def chain_merkle_block_serialized_size(self: MerkleBlock, version: int) -> int: ...

# ─── PrefilledTransaction (auto-generated, do not edit) ─────────────────────────

class PrefilledTransaction:
    """Opaque handle to a `kth::domain::message::prefilled_transaction`. Constructed by
    `chain_prefilled_transaction_construct_*` and released by
    `chain_prefilled_transaction_destruct`."""
    ...

def chain_prefilled_transaction_construct_default() -> PrefilledTransaction: ...
def chain_prefilled_transaction_construct_from_data(reader: bytes, version: int) -> PrefilledTransaction: ...
def chain_prefilled_transaction_construct(index: int, tx: "Transaction") -> PrefilledTransaction: ...
def chain_prefilled_transaction_copy(self: PrefilledTransaction) -> PrefilledTransaction: ...
def chain_prefilled_transaction_destruct(self: PrefilledTransaction) -> None: ...
def chain_prefilled_transaction_equals(self: PrefilledTransaction, other: PrefilledTransaction) -> bool: ...
def chain_prefilled_transaction_index(self: PrefilledTransaction) -> int: ...
def chain_prefilled_transaction_set_index(self: PrefilledTransaction, value: int) -> None: ...
def chain_prefilled_transaction_transaction(self: PrefilledTransaction) -> "Transaction" | None: ...
def chain_prefilled_transaction_set_transaction(self: PrefilledTransaction, tx: "Transaction") -> None: ...
def chain_prefilled_transaction_to_data(self: PrefilledTransaction, version: int) -> bytes: ...
def chain_prefilled_transaction_is_valid(self: PrefilledTransaction) -> bool: ...
def chain_prefilled_transaction_reset(self: PrefilledTransaction) -> None: ...
def chain_prefilled_transaction_serialized_size(self: PrefilledTransaction, version: int) -> int: ...

# ─── PrefilledTransactionList (auto-generated, do not edit) ─────────────────────────

class PrefilledTransactionList:
    """Opaque handle to a `std::vector<kth::domain::chain::prefilled_transaction>`."""
    ...

def chain_prefilled_transaction_list_construct_default() -> PrefilledTransactionList: ...
def chain_prefilled_transaction_list_push_back(list: PrefilledTransactionList, elem: PrefilledTransaction) -> None: ...
def chain_prefilled_transaction_list_destruct(list: PrefilledTransactionList) -> None: ...
def chain_prefilled_transaction_list_count(list: PrefilledTransactionList) -> int: ...
def chain_prefilled_transaction_list_nth(list: PrefilledTransactionList, index: int) -> PrefilledTransaction: ...
def chain_prefilled_transaction_list_assign_at(list: PrefilledTransactionList, index: int, elem: PrefilledTransaction) -> None: ...
def chain_prefilled_transaction_list_erase(list: PrefilledTransactionList, index: int) -> None: ...

# ─── CompactBlock (auto-generated, do not edit) ─────────────────────────

class CompactBlock:
    """Opaque handle to a `kth::domain::message::compact_block`. Constructed by
    `chain_compact_block_construct_*` and released by
    `chain_compact_block_destruct`."""
    ...

def chain_compact_block_construct_default() -> CompactBlock: ...
def chain_compact_block_construct_from_data(reader: bytes, version: int) -> CompactBlock: ...
def chain_compact_block_construct(header: "Header", nonce: int, short_ids: object, transactions: object) -> CompactBlock: ...
def chain_compact_block_copy(self: CompactBlock) -> CompactBlock: ...
def chain_compact_block_destruct(self: CompactBlock) -> None: ...
def chain_compact_block_equals(self: CompactBlock, other: CompactBlock) -> bool: ...
def chain_compact_block_header(self: CompactBlock) -> "Header" | None: ...
def chain_compact_block_set_header(self: CompactBlock, value: "Header") -> None: ...
def chain_compact_block_nonce(self: CompactBlock) -> int: ...
def chain_compact_block_set_nonce(self: CompactBlock, value: int) -> None: ...
def chain_compact_block_short_ids(self: CompactBlock) -> object | None: ...
def chain_compact_block_set_short_ids(self: CompactBlock, value: object) -> None: ...
def chain_compact_block_transactions(self: CompactBlock) -> "PrefilledTransactionList" | None: ...
def chain_compact_block_set_transactions(self: CompactBlock, value: object) -> None: ...
def chain_compact_block_to_data(self: CompactBlock, version: int) -> bytes: ...
def chain_compact_block_is_valid(self: CompactBlock) -> bool: ...
def chain_compact_block_reset(self: CompactBlock) -> None: ...
def chain_compact_block_serialized_size(self: CompactBlock, version: int) -> int: ...

# ─── PaymentAddress (auto-generated, do not edit) ─────────────────────────

class PaymentAddress:
    """Opaque handle to a `kth::domain::wallet::payment_address`. Constructed by
    `wallet_payment_address_construct_*` and released by
    `wallet_payment_address_destruct`."""
    ...

def wallet_payment_address_construct_default() -> PaymentAddress: ...
def wallet_payment_address_construct_from_decoded(decoded: bytes) -> PaymentAddress: ...
def wallet_payment_address_construct_from_ec_private(secret: "EcPrivate") -> PaymentAddress: ...
def wallet_payment_address_construct_from_address(address: str) -> PaymentAddress: ...
def wallet_payment_address_construct_from_address_net(address: str, net: int) -> PaymentAddress: ...
def wallet_payment_address_construct_from_short_hash_version(short_hash: bytes, version: int) -> PaymentAddress: ...
def wallet_payment_address_construct_from_hash_version(hash: bytes, version: int) -> PaymentAddress: ...
def wallet_payment_address_construct_from_ec_public_version(point: "EcPublic", version: int) -> PaymentAddress: ...
def wallet_payment_address_construct_from_script_version(script: "Script", version: int) -> PaymentAddress: ...
def wallet_payment_address_copy(self: PaymentAddress) -> PaymentAddress: ...
def wallet_payment_address_destruct(self: PaymentAddress) -> None: ...
def wallet_payment_address_cashaddr_prefix_for(net: int) -> str | None: ...
def wallet_payment_address_from_pay_public_key_hash_script(script: "Script", version: int) -> "PaymentAddress" | None: ...
def wallet_payment_address_equals(self: PaymentAddress, other: PaymentAddress) -> bool: ...
def wallet_payment_address_less(self: PaymentAddress, x: "PaymentAddress") -> bool: ...
def wallet_payment_address_valid(self: PaymentAddress) -> bool: ...
def wallet_payment_address_encoded_legacy(self: PaymentAddress) -> str | None: ...
def wallet_payment_address_encoded_cashaddr(self: PaymentAddress, token_aware: bool) -> str | None: ...
def wallet_payment_address_encoded_token(self: PaymentAddress) -> str | None: ...
def wallet_payment_address_version(self: PaymentAddress) -> int: ...
def wallet_payment_address_hash_span(self: PaymentAddress) -> object: ...
def wallet_payment_address_hash20(self: PaymentAddress) -> bytes: ...
def wallet_payment_address_hash32(self: PaymentAddress) -> bytes: ...
def wallet_payment_address_to_payment(self: PaymentAddress) -> bytes: ...
def wallet_payment_address_extract(script: "Script", p2kh_version: int, p2sh_version: int) -> "PaymentAddressList" | None: ...
def wallet_payment_address_extract_input(script: "Script", p2kh_version: int, p2sh_version: int) -> "PaymentAddressList" | None: ...
def wallet_payment_address_extract_output(script: "Script", p2kh_version: int, p2sh_version: int) -> "PaymentAddressList" | None: ...

# ─── PaymentAddressList (auto-generated, do not edit) ─────────────────────────

class PaymentAddressList:
    """Opaque handle to a `std::vector<kth::domain::wallet::payment_address>`."""
    ...

def wallet_payment_address_list_construct_default() -> PaymentAddressList: ...
def wallet_payment_address_list_push_back(list: PaymentAddressList, elem: PaymentAddress) -> None: ...
def wallet_payment_address_list_destruct(list: PaymentAddressList) -> None: ...
def wallet_payment_address_list_count(list: PaymentAddressList) -> int: ...
def wallet_payment_address_list_nth(list: PaymentAddressList, index: int) -> PaymentAddress: ...
def wallet_payment_address_list_assign_at(list: PaymentAddressList, index: int, elem: PaymentAddress) -> None: ...
def wallet_payment_address_list_erase(list: PaymentAddressList, index: int) -> None: ...

# ─── EcPublic (auto-generated, do not edit) ─────────────────────────

class EcPublic:
    """Opaque handle to a `kth::domain::wallet::ec_public`. Constructed by
    `wallet_ec_public_construct_*` and released by
    `wallet_ec_public_destruct`."""
    ...

def wallet_ec_public_construct_default() -> EcPublic: ...
def wallet_ec_public_construct_from_ec_private(secret: "EcPrivate") -> EcPublic: ...
def wallet_ec_public_construct_from_decoded(decoded: bytes) -> EcPublic: ...
def wallet_ec_public_construct_from_base16(base16: str) -> EcPublic: ...
def wallet_ec_public_construct_from_compressed_point_compress(compressed_point: bytes, compress: bool) -> EcPublic: ...
def wallet_ec_public_construct_from_uncompressed_point_compress(uncompressed_point: bytes, compress: bool) -> EcPublic: ...
def wallet_ec_public_copy(self: EcPublic) -> EcPublic: ...
def wallet_ec_public_destruct(self: EcPublic) -> None: ...
def wallet_ec_public_equals(self: EcPublic, other: EcPublic) -> bool: ...
def wallet_ec_public_less(self: EcPublic, x: "EcPublic") -> bool: ...
def wallet_ec_public_valid(self: EcPublic) -> bool: ...
def wallet_ec_public_encoded(self: EcPublic) -> str | None: ...
def wallet_ec_public_point(self: EcPublic) -> bytes: ...
def wallet_ec_public_compressed(self: EcPublic) -> bool: ...
def wallet_ec_public_to_data(self: EcPublic) -> bytes: ...
def wallet_ec_public_to_uncompressed(self: EcPublic) -> bytes: ...
def wallet_ec_public_to_payment_address(self: EcPublic, version: int) -> "PaymentAddress" | None: ...

# ─── EcPrivate (auto-generated, do not edit) ─────────────────────────

class EcPrivate:
    """Opaque handle to a `kth::domain::wallet::ec_private`. Constructed by
    `wallet_ec_private_construct_*` and released by
    `wallet_ec_private_destruct`."""
    ...

def wallet_ec_private_construct_default() -> EcPrivate: ...
def wallet_ec_private_construct_from_wif_version(wif: str, version: int) -> EcPrivate: ...
def wallet_ec_private_construct_from_wif_compressed_version(wif_compressed: bytes, version: int) -> EcPrivate: ...
def wallet_ec_private_construct_from_wif_uncompressed_version(wif_uncompressed: bytes, version: int) -> EcPrivate: ...
def wallet_ec_private_construct_from_secret_version_compress(secret: bytes, version: int, compress: bool) -> EcPrivate: ...
def wallet_ec_private_copy(self: EcPrivate) -> EcPrivate: ...
def wallet_ec_private_destruct(self: EcPrivate) -> None: ...
def wallet_ec_private_to_address_prefix(version: int) -> int: ...
def wallet_ec_private_to_wif_prefix(version: int) -> int: ...
def wallet_ec_private_to_version(address: int, wif: int) -> int: ...
def wallet_ec_private_equals(self: EcPrivate, other: EcPrivate) -> bool: ...
def wallet_ec_private_less(self: EcPrivate, x: "EcPrivate") -> bool: ...
def wallet_ec_private_valid(self: EcPrivate) -> bool: ...
def wallet_ec_private_encoded(self: EcPrivate) -> str | None: ...
def wallet_ec_private_secret(self: EcPrivate) -> bytes: ...
def wallet_ec_private_version(self: EcPrivate) -> int: ...
def wallet_ec_private_payment_version(self: EcPrivate) -> int: ...
def wallet_ec_private_wif_version(self: EcPrivate) -> int: ...
def wallet_ec_private_compressed(self: EcPrivate) -> bool: ...
def wallet_ec_private_to_public(self: EcPrivate) -> "EcPublic" | None: ...
def wallet_ec_private_to_payment_address(self: EcPrivate) -> "PaymentAddress" | None: ...

# ─── Operation (auto-generated, do not edit) ─────────────────────────

class Operation:
    """Opaque handle to a `kth::domain::machine::operation`. Constructed by
    `chain_operation_construct_*` and released by
    `chain_operation_destruct`."""
    ...

def chain_operation_construct_default() -> Operation: ...
def chain_operation_construct_from_data(reader: bytes) -> Operation: ...
def chain_operation_construct_from_uncoded_minimal(uncoded: bytes, minimal: bool) -> Operation: ...
def chain_operation_construct_from_code(code: int) -> Operation: ...
def chain_operation_copy(self: Operation) -> Operation: ...
def chain_operation_destruct(self: Operation) -> None: ...
def chain_operation_equals(self: Operation, other: Operation) -> bool: ...
def chain_operation_from_string(self: Operation, mnemonic: str) -> bool: ...
def chain_operation_is_valid(self: Operation) -> bool: ...
def chain_operation_to_data(self: Operation) -> bytes: ...
def chain_operation_to_string(self: Operation, active_flags: int) -> str | None: ...
def chain_operation_serialized_size(self: Operation) -> int: ...
def chain_operation_code(self: Operation) -> int: ...
def chain_operation_data(self: Operation) -> bytes: ...
def chain_operation_opcode_from_size(size: int) -> int: ...
def chain_operation_minimal_opcode_from_data(data: bytes) -> int: ...
def chain_operation_nominal_opcode_from_data(data: bytes) -> int: ...
def chain_operation_opcode_from_positive(value: int) -> int: ...
def chain_operation_opcode_to_positive(code: int) -> int: ...
def chain_operation_is_push(code: int) -> bool: ...
def chain_operation_is_payload(code: int) -> bool: ...
def chain_operation_is_counted(code: int) -> bool: ...
def chain_operation_is_version(code: int) -> bool: ...
def chain_operation_is_numeric(code: int) -> bool: ...
def chain_operation_is_positive(code: int) -> bool: ...
def chain_operation_is_reserved(code: int) -> bool: ...
def chain_operation_is_disabled(code: int, active_flags: int) -> bool: ...
def chain_operation_is_conditional(code: int) -> bool: ...
def chain_operation_is_relaxed_push(code: int) -> bool: ...
def chain_operation_is_push_simple(self: Operation) -> bool: ...
def chain_operation_is_counted_simple(self: Operation) -> bool: ...
def chain_operation_is_version_simple(self: Operation) -> bool: ...
def chain_operation_is_positive_simple(self: Operation) -> bool: ...
def chain_operation_is_disabled_simple(self: Operation, active_flags: int) -> bool: ...
def chain_operation_is_conditional_simple(self: Operation) -> bool: ...
def chain_operation_is_relaxed_push_simple(self: Operation) -> bool: ...
def chain_operation_is_oversized(self: Operation, max_size: int) -> bool: ...
def chain_operation_is_minimal_push(self: Operation) -> bool: ...
def chain_operation_is_nominal_push(self: Operation) -> bool: ...

# ─── OperationList (auto-generated, do not edit) ─────────────────────────

class OperationList:
    """Opaque handle to a `std::vector<kth::domain::chain::operation>`."""
    ...

def chain_operation_list_construct_default() -> OperationList: ...
def chain_operation_list_push_back(list: OperationList, elem: Operation) -> None: ...
def chain_operation_list_destruct(list: OperationList) -> None: ...
def chain_operation_list_count(list: OperationList) -> int: ...
def chain_operation_list_nth(list: OperationList, index: int) -> Operation: ...
def chain_operation_list_assign_at(list: OperationList, index: int, elem: Operation) -> None: ...
def chain_operation_list_erase(list: OperationList, index: int) -> None: ...

# ─── HdPublic (auto-generated, do not edit) ─────────────────────────

class HdPublic:
    """Opaque handle to a `kth::domain::wallet::hd_public`. Constructed by
    `wallet_hd_public_construct_*` and released by
    `wallet_hd_public_destruct`."""
    ...

def wallet_hd_public_construct_default() -> HdPublic: ...
def wallet_hd_public_construct_from_public_key(public_key: bytes) -> HdPublic: ...
def wallet_hd_public_construct_from_public_key_prefix(public_key: bytes, prefix: int) -> HdPublic: ...
def wallet_hd_public_construct_from_encoded(encoded: str) -> HdPublic: ...
def wallet_hd_public_construct_from_encoded_prefix(encoded: str, prefix: int) -> HdPublic: ...
def wallet_hd_public_copy(self: HdPublic) -> HdPublic: ...
def wallet_hd_public_destruct(self: HdPublic) -> None: ...
def wallet_hd_public_to_prefix(prefixes: int) -> int: ...
def wallet_hd_public_less(self: HdPublic, x: "HdPublic") -> bool: ...
def wallet_hd_public_equals(self: HdPublic, other: HdPublic) -> bool: ...
def wallet_hd_public_valid(self: HdPublic) -> bool: ...
def wallet_hd_public_encoded(self: HdPublic) -> str | None: ...
def wallet_hd_public_chain_code(self: HdPublic) -> bytes: ...
def wallet_hd_public_lineage(self: HdPublic) -> tuple[int, ...]: ...
def wallet_hd_public_point(self: HdPublic) -> bytes: ...
def wallet_hd_public_to_hd_key(self: HdPublic) -> bytes: ...
def wallet_hd_public_derive_public(self: HdPublic, index: int) -> "HdPublic" | None: ...

# ─── HdPrivate (auto-generated, do not edit) ─────────────────────────

class HdPrivate:
    """Opaque handle to a `kth::domain::wallet::hd_private`. Constructed by
    `wallet_hd_private_construct_*` and released by
    `wallet_hd_private_destruct`."""
    ...

def wallet_hd_private_construct_default() -> HdPrivate: ...
def wallet_hd_private_construct_from_seed_prefixes(seed: bytes, prefixes: int) -> HdPrivate: ...
def wallet_hd_private_construct_from_private_key(private_key: bytes) -> HdPrivate: ...
def wallet_hd_private_construct_from_private_key_prefixes(private_key: bytes, prefixes: int) -> HdPrivate: ...
def wallet_hd_private_construct_from_private_key_prefix(private_key: bytes, prefix: int) -> HdPrivate: ...
def wallet_hd_private_construct_from_encoded(encoded: str) -> HdPrivate: ...
def wallet_hd_private_construct_from_encoded_prefixes(encoded: str, prefixes: int) -> HdPrivate: ...
def wallet_hd_private_construct_from_encoded_prefix(encoded: str, prefix: int) -> HdPrivate: ...
def wallet_hd_private_copy(self: HdPrivate) -> HdPrivate: ...
def wallet_hd_private_destruct(self: HdPrivate) -> None: ...
def wallet_hd_private_to_prefix(prefixes: int) -> int: ...
def wallet_hd_private_less(self: HdPrivate, x: "HdPrivate") -> bool: ...
def wallet_hd_private_equals(self: HdPrivate, other: HdPrivate) -> bool: ...
def wallet_hd_private_encoded(self: HdPrivate) -> str | None: ...
def wallet_hd_private_secret(self: HdPrivate) -> bytes: ...
def wallet_hd_private_to_hd_key(self: HdPrivate) -> bytes: ...
def wallet_hd_private_to_public(self: HdPrivate) -> "HdPublic" | None: ...
def wallet_hd_private_derive_private(self: HdPrivate, index: int) -> "HdPrivate" | None: ...
def wallet_hd_private_derive_public(self: HdPrivate, index: int) -> "HdPublic" | None: ...
def wallet_hd_private_valid(self: HdPrivate) -> bool: ...
def wallet_hd_private_chain_code(self: HdPrivate) -> bytes: ...
def wallet_hd_private_lineage(self: HdPrivate) -> tuple[int, ...]: ...
def wallet_hd_private_point(self: HdPrivate) -> bytes: ...

# ─── StealthCompact (auto-generated, do not edit) ─────────────────────────

class StealthCompact:
    """Opaque handle to a `kth::domain::chain::stealth_compact`. Constructed by
    `chain_stealth_compact_construct_*` and released by
    `chain_stealth_compact_destruct`."""
    ...

def chain_stealth_compact_copy(self: StealthCompact) -> StealthCompact: ...
def chain_stealth_compact_destruct(self: StealthCompact) -> None: ...
def chain_stealth_compact_ephemeral_public_key_hash(self: StealthCompact) -> bytes: ...
def chain_stealth_compact_set_ephemeral_public_key_hash(self: StealthCompact, value: bytes) -> None: ...
def chain_stealth_compact_public_key_hash(self: StealthCompact) -> bytes: ...
def chain_stealth_compact_set_public_key_hash(self: StealthCompact, value: bytes) -> None: ...
def chain_stealth_compact_transaction_hash(self: StealthCompact) -> bytes: ...
def chain_stealth_compact_set_transaction_hash(self: StealthCompact, value: bytes) -> None: ...

# ─── StealthCompactList (auto-generated, do not edit) ─────────────────────────

class StealthCompactList:
    """Opaque handle to a `std::vector<kth::domain::chain::stealth_compact>`."""
    ...

def chain_stealth_compact_list_construct_default() -> StealthCompactList: ...
def chain_stealth_compact_list_push_back(list: StealthCompactList, elem: StealthCompact) -> None: ...
def chain_stealth_compact_list_destruct(list: StealthCompactList) -> None: ...
def chain_stealth_compact_list_count(list: StealthCompactList) -> int: ...
def chain_stealth_compact_list_nth(list: StealthCompactList, index: int) -> StealthCompact: ...
def chain_stealth_compact_list_assign_at(list: StealthCompactList, index: int, elem: StealthCompact) -> None: ...
def chain_stealth_compact_list_erase(list: StealthCompactList, index: int) -> None: ...

# ─── HistoryCompact (auto-generated, do not edit) ─────────────────────────

class HistoryCompact:
    """Opaque handle to a `kth::domain::chain::history_compact`. Constructed by
    `chain_history_compact_construct_*` and released by
    `chain_history_compact_destruct`."""
    ...

def chain_history_compact_copy(self: HistoryCompact) -> HistoryCompact: ...
def chain_history_compact_destruct(self: HistoryCompact) -> None: ...
def chain_history_compact_kind(self: HistoryCompact) -> int: ...
def chain_history_compact_set_kind(self: HistoryCompact, value: int) -> None: ...
def chain_history_compact_point(self: HistoryCompact) -> "Point" | None: ...
def chain_history_compact_set_point(self: HistoryCompact, value: "Point") -> None: ...
def chain_history_compact_height(self: HistoryCompact) -> int: ...
def chain_history_compact_set_height(self: HistoryCompact, value: int) -> None: ...
def chain_history_compact_value_or_previous_checksum(self: HistoryCompact) -> int: ...
def chain_history_compact_set_value_or_previous_checksum(self: HistoryCompact, value: int) -> None: ...

# ─── HistoryCompactList (auto-generated, do not edit) ─────────────────────────

class HistoryCompactList:
    """Opaque handle to a `std::vector<kth::domain::chain::history_compact>`."""
    ...

def chain_history_compact_list_construct_default() -> HistoryCompactList: ...
def chain_history_compact_list_push_back(list: HistoryCompactList, elem: HistoryCompact) -> None: ...
def chain_history_compact_list_destruct(list: HistoryCompactList) -> None: ...
def chain_history_compact_list_count(list: HistoryCompactList) -> int: ...
def chain_history_compact_list_nth(list: HistoryCompactList, index: int) -> HistoryCompact: ...
def chain_history_compact_list_assign_at(list: HistoryCompactList, index: int, elem: HistoryCompact) -> None: ...
def chain_history_compact_list_erase(list: HistoryCompactList, index: int) -> None: ...

# ─── DoubleSpendProof (auto-generated, do not edit) ─────────────────────────

class DoubleSpendProof:
    """Opaque handle to a `kth::domain::message::double_spend_proof`. Constructed by
    `chain_double_spend_proof_construct_*` and released by
    `chain_double_spend_proof_destruct`."""
    ...

def chain_double_spend_proof_construct_default() -> DoubleSpendProof: ...
def chain_double_spend_proof_construct_from_data(reader: bytes, version: int) -> DoubleSpendProof: ...
def chain_double_spend_proof_construct(out_point: "OutputPoint", spender1: "DoubleSpendProofSpender", spender2: "DoubleSpendProofSpender") -> DoubleSpendProof: ...
def chain_double_spend_proof_copy(self: DoubleSpendProof) -> DoubleSpendProof: ...
def chain_double_spend_proof_destruct(self: DoubleSpendProof) -> None: ...
def chain_double_spend_proof_equals(self: DoubleSpendProof, other: DoubleSpendProof) -> bool: ...
def chain_double_spend_proof_out_point(self: DoubleSpendProof) -> "OutputPoint" | None: ...
def chain_double_spend_proof_set_out_point(self: DoubleSpendProof, x: "OutputPoint") -> None: ...
def chain_double_spend_proof_spender1(self: DoubleSpendProof) -> "DoubleSpendProofSpender" | None: ...
def chain_double_spend_proof_set_spender1(self: DoubleSpendProof, x: "DoubleSpendProofSpender") -> None: ...
def chain_double_spend_proof_spender2(self: DoubleSpendProof) -> "DoubleSpendProofSpender" | None: ...
def chain_double_spend_proof_set_spender2(self: DoubleSpendProof, x: "DoubleSpendProofSpender") -> None: ...
def chain_double_spend_proof_to_data(self: DoubleSpendProof, version: int) -> bytes: ...
def chain_double_spend_proof_is_valid(self: DoubleSpendProof) -> bool: ...
def chain_double_spend_proof_reset(self: DoubleSpendProof) -> None: ...
def chain_double_spend_proof_serialized_size(self: DoubleSpendProof, version: int) -> int: ...
def chain_double_spend_proof_hash(self: DoubleSpendProof) -> bytes: ...

# ─── DoubleSpendProofSpender (auto-generated, do not edit) ─────────────────────────

class DoubleSpendProofSpender:
    """Opaque handle to a `kth::domain::message::double_spend_proof::spender`. Constructed by
    `chain_double_spend_proof_spender_construct_*` and released by
    `chain_double_spend_proof_spender_destruct`."""
    ...

def chain_double_spend_proof_spender_construct_from_data(reader: bytes, version: int) -> DoubleSpendProofSpender: ...
def chain_double_spend_proof_spender_copy(self: DoubleSpendProofSpender) -> DoubleSpendProofSpender: ...
def chain_double_spend_proof_spender_destruct(self: DoubleSpendProofSpender) -> None: ...
def chain_double_spend_proof_spender_version(self: DoubleSpendProofSpender) -> int: ...
def chain_double_spend_proof_spender_set_version(self: DoubleSpendProofSpender, value: int) -> None: ...
def chain_double_spend_proof_spender_out_sequence(self: DoubleSpendProofSpender) -> int: ...
def chain_double_spend_proof_spender_set_out_sequence(self: DoubleSpendProofSpender, value: int) -> None: ...
def chain_double_spend_proof_spender_locktime(self: DoubleSpendProofSpender) -> int: ...
def chain_double_spend_proof_spender_set_locktime(self: DoubleSpendProofSpender, value: int) -> None: ...
def chain_double_spend_proof_spender_prev_outs_hash(self: DoubleSpendProofSpender) -> bytes: ...
def chain_double_spend_proof_spender_set_prev_outs_hash(self: DoubleSpendProofSpender, value: bytes) -> None: ...
def chain_double_spend_proof_spender_sequence_hash(self: DoubleSpendProofSpender) -> bytes: ...
def chain_double_spend_proof_spender_set_sequence_hash(self: DoubleSpendProofSpender, value: bytes) -> None: ...
def chain_double_spend_proof_spender_outputs_hash(self: DoubleSpendProofSpender) -> bytes: ...
def chain_double_spend_proof_spender_set_outputs_hash(self: DoubleSpendProofSpender, value: bytes) -> None: ...
def chain_double_spend_proof_spender_push_data(self: DoubleSpendProofSpender) -> bytes: ...
def chain_double_spend_proof_spender_set_push_data(self: DoubleSpendProofSpender, value: bytes) -> None: ...
def chain_double_spend_proof_spender_is_valid(self: DoubleSpendProofSpender) -> bool: ...
def chain_double_spend_proof_spender_reset(self: DoubleSpendProofSpender) -> None: ...
def chain_double_spend_proof_spender_equals(self: DoubleSpendProofSpender, other: DoubleSpendProofSpender) -> bool: ...
def chain_double_spend_proof_spender_serialized_size(self: DoubleSpendProofSpender) -> int: ...

# ─── TokenData (auto-generated, do not edit) ─────────────────────────

class TokenData:
    """Opaque handle to a `kth::domain::chain::token_data_t`. Constructed by
    `chain_token_data_construct_*` and released by
    `chain_token_data_destruct`."""
    ...

def chain_token_data_construct_from_data(reader: bytes) -> TokenData: ...
def chain_token_data_copy(self: TokenData) -> TokenData: ...
def chain_token_data_destruct(self: TokenData) -> None: ...
def chain_token_data_id(self: TokenData) -> bytes: ...
def chain_token_data_set_id(self: TokenData, value: bytes) -> None: ...
def chain_token_data_equals(self: TokenData, other: TokenData) -> bool: ...
def chain_token_data_make_fungible(id: bytes, amount: int) -> "TokenData" | None: ...
def chain_token_data_make_non_fungible(id: bytes, capability: int, commitment: bytes) -> "TokenData" | None: ...
def chain_token_data_make_both(id: bytes, amount: int, capability: int, commitment: bytes) -> "TokenData" | None: ...
def chain_token_data_get_kind(self: TokenData) -> int: ...
def chain_token_data_is_valid(self: TokenData) -> bool: ...
def chain_token_data_get_amount(self: TokenData) -> int: ...
def chain_token_data_has_nft(self: TokenData) -> bool: ...
def chain_token_data_is_fungible_only(self: TokenData) -> bool: ...
def chain_token_data_get_nft_capability(self: TokenData) -> int: ...
def chain_token_data_get_nft_commitment(self: TokenData) -> bytes: ...
def chain_token_data_is_immutable_nft(self: TokenData) -> bool: ...
def chain_token_data_is_mutable_nft(self: TokenData) -> bool: ...
def chain_token_data_is_minting_nft(self: TokenData) -> bool: ...
def chain_token_data_serialized_size(self: TokenData) -> int: ...
def chain_token_data_bitfield(self: TokenData) -> int: ...
def chain_token_data_to_data(self: TokenData) -> bytes: ...

# ─── Utxo (auto-generated, do not edit) ─────────────────────────

class Utxo:
    """Opaque handle to a `kth::domain::chain::utxo`. Constructed by
    `chain_utxo_construct_*` and released by
    `chain_utxo_destruct`."""
    ...

def chain_utxo_construct_default() -> Utxo: ...
def chain_utxo_copy(self: Utxo) -> Utxo: ...
def chain_utxo_destruct(self: Utxo) -> None: ...
def chain_utxo_equals(self: Utxo, other: Utxo) -> bool: ...
def chain_utxo_height(self: Utxo) -> int: ...
def chain_utxo_point(self: Utxo) -> "OutputPoint" | None: ...
def chain_utxo_amount(self: Utxo) -> int: ...
def chain_utxo_set_height(self: Utxo, height: int) -> None: ...
def chain_utxo_set_point(self: Utxo, point: "OutputPoint") -> None: ...
def chain_utxo_set_amount(self: Utxo, amount: int) -> None: ...

# ─── UtxoList (auto-generated, do not edit) ─────────────────────────

class UtxoList:
    """Opaque handle to a `std::vector<kth::domain::chain::utxo>`."""
    ...

def chain_utxo_list_construct_default() -> UtxoList: ...
def chain_utxo_list_push_back(list: UtxoList, elem: Utxo) -> None: ...
def chain_utxo_list_destruct(list: UtxoList) -> None: ...
def chain_utxo_list_count(list: UtxoList) -> int: ...
def chain_utxo_list_nth(list: UtxoList, index: int) -> Utxo: ...
def chain_utxo_list_assign_at(list: UtxoList, index: int, elem: Utxo) -> None: ...
def chain_utxo_list_erase(list: UtxoList, index: int) -> None: ...

# ─── Program (auto-generated, do not edit) ─────────────────────────

class Program:
    """Opaque handle to a `kth::domain::machine::program`. Constructed by
    `vm_program_construct_*` and released by
    `vm_program_destruct`."""
    ...

def vm_program_construct_default() -> Program: ...
def vm_program_construct_from_script(script: "Script") -> Program: ...
def vm_program_construct_from_script_transaction_input_index_flags_value(script: "Script", transaction: "Transaction", input_index: int, flags: int, value: int) -> Program: ...
def vm_program_construct_from_script_transaction_input_index_flags_stack_value(script: "Script", transaction: "Transaction", input_index: int, flags: int, stack: object, value: int) -> Program: ...
def vm_program_construct_from_script_program(script: "Script", x: "Program") -> Program: ...
def vm_program_construct_from_script_program_move(script: "Script", x: "Program", move: bool) -> Program: ...
def vm_program_copy(self: Program) -> Program: ...
def vm_program_destruct(self: Program) -> None: ...
def vm_program_get_metrics(self: Program) -> "Metrics" | None: ...
def vm_program_is_valid(self: Program) -> bool: ...
def vm_program_flags(self: Program) -> int: ...
def vm_program_max_script_element_size(self: Program) -> int: ...
def vm_program_max_integer_size_legacy(self: Program) -> int: ...
def vm_program_max_integer_size(self: Program) -> int: ...
def vm_program_is_chip_vm_limits_enabled(self: Program) -> bool: ...
def vm_program_is_bigint_enabled(self: Program) -> bool: ...
def vm_program_input_index(self: Program) -> int: ...
def vm_program_value(self: Program) -> int: ...
def vm_program_transaction(self: Program) -> "Transaction" | None: ...
def vm_program_get_script(self: Program) -> "Script" | None: ...
def vm_program_reset_active_script(self: Program) -> None: ...
def vm_program_operation_count(self: Program) -> int: ...
def vm_program_evaluate_simple(self: Program) -> int: ...
def vm_program_evaluate(self: Program, op: "Operation") -> int: ...
def vm_program_increment_operation_count_operation(self: Program, op: "Operation") -> bool: ...
def vm_program_increment_operation_count_int32(self: Program, public_keys: int) -> bool: ...
def vm_program_mark_code_separator(self: Program, pc: int) -> bool: ...
def vm_program_push(self: Program, value: bool) -> None: ...
def vm_program_push_move(self: Program, item: bytes) -> None: ...
def vm_program_push_copy(self: Program, item: bytes) -> None: ...
def vm_program_drop(self: Program) -> None: ...
def vm_program_pop(self: Program) -> bytes: ...
def vm_program_duplicate(self: Program, index: int) -> None: ...
def vm_program_swap(self: Program, index_left: int, index_right: int) -> None: ...
def vm_program_empty(self: Program) -> bool: ...
def vm_program_stack_true(self: Program, clean: bool) -> bool: ...
def vm_program_stack_result(self: Program, clean: bool) -> bool: ...
def vm_program_is_stack_overflow_simple(self: Program) -> bool: ...
def vm_program_is_stack_overflow(self: Program, extra: int) -> bool: ...
def vm_program_if_(self: Program, op: "Operation") -> bool: ...
def vm_program_item(self: Program, index: int) -> bytes: ...
def vm_program_top(self: Program) -> bytes: ...
def vm_program_subscript(self: Program) -> "OperationList" | None: ...
def vm_program_size(self: Program) -> int: ...
def vm_program_conditional_stack_size(self: Program) -> int: ...
def vm_program_empty_alternate(self: Program) -> bool: ...
def vm_program_push_alternate(self: Program, value: bytes) -> None: ...
def vm_program_pop_alternate(self: Program) -> bytes: ...
def vm_program_open(self: Program, value: bool) -> None: ...
def vm_program_negate(self: Program) -> None: ...
def vm_program_close(self: Program) -> None: ...
def vm_program_closed(self: Program) -> bool: ...
def vm_program_succeeded(self: Program) -> bool: ...

# ─── DebugSnapshot (auto-generated, do not edit) ─────────────────────────

class DebugSnapshot:
    """Opaque handle to a `kth::domain::machine::debug_snapshot`. Constructed by
    `vm_debug_snapshot_construct_*` and released by
    `vm_debug_snapshot_destruct`."""
    ...

def vm_debug_snapshot_construct_default() -> DebugSnapshot: ...
def vm_debug_snapshot_construct(p: "Program") -> DebugSnapshot: ...
def vm_debug_snapshot_copy(self: DebugSnapshot) -> DebugSnapshot: ...
def vm_debug_snapshot_destruct(self: DebugSnapshot) -> None: ...
def vm_debug_snapshot_prog(self: DebugSnapshot) -> "Program" | None: ...
def vm_debug_snapshot_step(self: DebugSnapshot) -> int: ...
def vm_debug_snapshot_last(self: DebugSnapshot) -> int: ...
def vm_debug_snapshot_done(self: DebugSnapshot) -> bool: ...
def vm_debug_snapshot_control_stack(self: DebugSnapshot) -> object | None: ...
def vm_debug_snapshot_loop_stack(self: DebugSnapshot) -> object | None: ...
def vm_debug_snapshot_invoke_depth(self: DebugSnapshot) -> int: ...
def vm_debug_snapshot_outer_loop_depth(self: DebugSnapshot) -> int: ...

# ─── DebugSnapshotList (auto-generated, do not edit) ─────────────────────────

class DebugSnapshotList:
    """Opaque handle to a `std::vector<kth::domain::chain::debug_snapshot>`."""
    ...

def vm_debug_snapshot_list_construct_default() -> DebugSnapshotList: ...
def vm_debug_snapshot_list_push_back(list: DebugSnapshotList, elem: DebugSnapshot) -> None: ...
def vm_debug_snapshot_list_destruct(list: DebugSnapshotList) -> None: ...
def vm_debug_snapshot_list_count(list: DebugSnapshotList) -> int: ...
def vm_debug_snapshot_list_nth(list: DebugSnapshotList, index: int) -> DebugSnapshot: ...
def vm_debug_snapshot_list_assign_at(list: DebugSnapshotList, index: int, elem: DebugSnapshot) -> None: ...
def vm_debug_snapshot_list_erase(list: DebugSnapshotList, index: int) -> None: ...

# ─── Interpreter (auto-generated, do not edit) ─────────────────────────

class Interpreter:
    """Opaque handle to a `kth::domain::machine::interpreter`. Constructed by
    `vm_interpreter_construct_*` and released by
    `vm_interpreter_destruct`."""
    ...

def vm_interpreter_run_simple(program: "Program") -> int: ...
def vm_interpreter_run(op: "Operation", program: "Program") -> int: ...
def vm_interpreter_debug_begin(prog: "Program") -> "DebugSnapshot" | None: ...
def vm_interpreter_debug_step(snapshot: "DebugSnapshot") -> "DebugSnapshot" | None: ...
def vm_interpreter_debug_step_n(snapshot: "DebugSnapshot", n: int) -> "DebugSnapshot" | None: ...
def vm_interpreter_debug_run(snapshot: "DebugSnapshot") -> "DebugSnapshot" | None: ...
def vm_interpreter_debug_run_traced(start: "DebugSnapshot") -> "DebugSnapshotList" | None: ...
def vm_interpreter_debug_finalize(snapshot: "DebugSnapshot") -> int: ...

# ─── Metrics (auto-generated, do not edit) ─────────────────────────

class Metrics:
    """Opaque handle to a `kth::domain::machine::metrics`. Constructed by
    `vm_metrics_construct_*` and released by
    `vm_metrics_destruct`."""
    ...

def vm_metrics_copy(self: Metrics) -> Metrics: ...
def vm_metrics_destruct(self: Metrics) -> None: ...
def vm_metrics_sig_checks(self: Metrics) -> int: ...
def vm_metrics_op_cost(self: Metrics) -> int: ...
def vm_metrics_hash_digest_iterations(self: Metrics) -> int: ...
def vm_metrics_add_op_cost(self: Metrics, cost: int) -> None: ...
def vm_metrics_add_push_op(self: Metrics, stack_item_length: int) -> None: ...
def vm_metrics_add_hash_iterations(self: Metrics, message_length: int, is_two_round_hash: bool) -> None: ...
def vm_metrics_add_sig_checks(self: Metrics, n_checks: int) -> None: ...
def vm_metrics_is_over_op_cost_limit(self: Metrics, flags: int) -> bool: ...
def vm_metrics_is_over_op_cost_limit_simple(self: Metrics) -> bool: ...
def vm_metrics_is_over_hash_iters_limit(self: Metrics) -> bool: ...
def vm_metrics_has_valid_script_limits(self: Metrics) -> bool: ...
def vm_metrics_set_script_limits(self: Metrics, flags: int, script_sig_size: int) -> None: ...
def vm_metrics_set_native_script_limits(self: Metrics, standard: bool, script_sig_size: int) -> None: ...
def vm_metrics_composite_op_cost_script_flags(self: Metrics, flags: int) -> int: ...
def vm_metrics_composite_op_cost_bool(self: Metrics, standard: bool) -> int: ...

# ─── WalletData (auto-generated, do not edit) ─────────────────────────

class WalletData:
    """Opaque handle to a `kth::domain::wallet::wallet_data`. Constructed by
    `wallet_wallet_data_construct_*` and released by
    `wallet_wallet_data_destruct`."""
    ...

def wallet_wallet_data_copy(self: WalletData) -> WalletData: ...
def wallet_wallet_data_destruct(self: WalletData) -> None: ...
def wallet_wallet_data_mnemonics(self: WalletData) -> object | None: ...
def wallet_wallet_data_set_mnemonics(self: WalletData, value: object) -> None: ...
def wallet_wallet_data_xpub(self: WalletData) -> "HdPublic" | None: ...
def wallet_wallet_data_set_xpub(self: WalletData, value: "HdPublic") -> None: ...
def wallet_wallet_data_encrypted_seed(self: WalletData) -> bytes: ...
def wallet_wallet_data_set_encrypted_seed(self: WalletData, value: bytes) -> None: ...
def wallet_wallet_data_create(password: str, normalized_passphrase: str) -> "WalletData": ...
# ── AUTO-GENERATED STUBS END ────────────────────────────────────────
