# Copyright (c) 2016-present Knuth Project developers.
# Distributed under the MIT software license, see the accompanying
# file COPYING or http://www.opensource.org/licenses/mit-license.php.

# pyright: strict
"""Type stubs for the `kth_native` CPython extension.

The hand-written sections cover:

* the eight Python-visible types exposed by the C extension
  (`Settings`, `BlockchainSettings`, `DatabaseSettings`,
  `NetworkSettings`, `NodeSettings`, `Authority`, `Endpoint`,
  `Checkpoint`), with every member that ships in the modern C-API; and

* the small set of "front-door" functions that downstream consumers
  (most notably `py-api`) actually call by hand: `node_*`, `config_*`,
  `wallet_payment_address_*`, the per-network helpers, and the chain
  fetch entry points.

Everything else (most of the 169 `chain_*` helpers — block / header /
transaction / input / output / script / merkle / history / stealth
plumbing) is enumerated below as `(*args, **kwargs) -> Any` so that
IDE name-completion and "is this exported?" checks still work, while
keeping this file maintainable. Type those in a follow-up pass when a
specific call site needs strict signatures.
"""

from __future__ import annotations

from collections.abc import Callable
from typing import Any, Final

# ─────────────────────────────────────────────────────────────────────
# Enums (modeled as Final ints — the C-API doesn't ship Python enums)
# ─────────────────────────────────────────────────────────────────────

# kth_network_t — values must match the kth-c-api primitives.h enum.
NETWORK_MAINNET: Final[int] = 0
NETWORK_TESTNET: Final[int] = 1
NETWORK_REGTEST: Final[int] = 2
NETWORK_TESTNET4: Final[int] = 3
NETWORK_SCALENET: Final[int] = 4
NETWORK_CHIPNET: Final[int] = 5

# kth_db_mode_t
DB_MODE_PRUNED: Final[int] = 0
DB_MODE_NORMAL: Final[int] = 1
DB_MODE_FULL_INDEXED: Final[int] = 2

# StartModules — values for the second arg of node_init_run_and_wait_for_signal.
START_MODULES_JUST_CHAIN: Final[int] = 1
START_MODULES_FULL: Final[int] = 2

# ─────────────────────────────────────────────────────────────────────
# Settings types
# ─────────────────────────────────────────────────────────────────────

class NodeSettings:
    """Mirror of `kth_node_settings`."""

    sync_peers: int
    sync_timeout_seconds: int
    block_latency_seconds: int
    refresh_transactions: bool
    compact_blocks_high_bandwidth: bool
    ds_proofs_enabled: bool

    def __init__(self) -> None: ...


class DatabaseSettings:
    """Mirror of `kth_database_settings`."""

    directory: str
    db_mode: int  # one of DB_MODE_*
    reorg_pool_limit: int
    db_max_size: int
    safe_mode: bool
    cache_capacity: int

    def __init__(self) -> None: ...


class Checkpoint:
    """Mirror of `kth_checkpoint`."""

    hash: bytes  # 32 bytes, big-endian (display order)
    height: int

    def __init__(self) -> None: ...


class Authority:
    """Mirror of `kth_authority` — host:port pair."""

    ip: str
    port: int

    def __init__(self) -> None: ...


class Endpoint:
    """Mirror of `kth_endpoint` — scheme://host:port triple."""

    scheme: str
    host: str
    port: int

    def __init__(self) -> None: ...


class BlockchainSettings:
    """Mirror of `kth_blockchain_settings`. BCH-specific fields are
    only meaningful when the build was compiled with `KTH_CURRENCY_BCH`."""

    cores: int
    priority: bool
    byte_fee_satoshis: float
    sigop_fee_satoshis: float
    minimum_output_satoshis: int
    notify_limit_hours: int
    reorganization_limit: int
    checkpoints: list[Checkpoint]
    fix_checkpoints: bool
    allow_collisions: bool
    easy_blocks: bool
    retarget: bool

    # BIPs (consensus toggles).
    bip16: bool
    bip30: bool
    bip34: bool
    bip66: bool
    bip65: bool
    bip90: bool
    bip68: bool
    bip112: bool
    bip113: bool

    # BCH hard-forks (already activated on every shipped network).
    bch_uahf: bool
    bch_daa_cw144: bool
    bch_pythagoras: bool
    bch_euclid: bool
    bch_pisano: bool
    bch_mersenne: bool
    bch_fermat: bool
    bch_euler: bool
    bch_gauss: bool
    bch_descartes: bool
    bch_lobachevski: bool
    bch_galois: bool

    # Future hard-forks: timestamps only, the bool flags will be added
    # in a later kth release.
    leibniz_activation_time: int  # 2026-May
    cantor_activation_time: int   # 2027-May

    asert_half_life: int

    def __init__(self) -> None: ...


class NetworkSettings:
    """Mirror of `kth_network_settings`."""

    threads: int
    protocol_maximum: int
    protocol_minimum: int
    services: int
    invalid_services: int
    relay_transactions: bool
    validate_checksum: bool
    identifier: int
    inbound_port: int
    inbound_connections: int
    outbound_connections: int
    manual_attempt_limit: int
    connect_batch_size: int
    connect_timeout_seconds: int
    channel_handshake_seconds: int
    channel_heartbeat_minutes: int
    channel_inactivity_minutes: int
    channel_expiration_minutes: int
    channel_germination_seconds: int
    host_pool_capacity: int
    hosts_file: str
    self: Authority
    blacklist: list[Authority]
    peers: list[Endpoint]
    seeds: list[Endpoint]
    debug_file: str
    error_file: str
    archive_directory: str
    rotation_size: int
    minimum_free_space: int
    maximum_archive_size: int
    maximum_archive_files: int
    statistics_server: Authority
    verbose: bool
    use_ipv6: bool
    user_agent_blacklist: list[str]

    def __init__(self) -> None: ...


class Settings:
    """Mirror of `kth_settings` — the top-level config bundle."""

    node: NodeSettings
    chain: BlockchainSettings
    database: DatabaseSettings
    network: NetworkSettings

    def __init__(self) -> None: ...


# ─────────────────────────────────────────────────────────────────────
# Opaque handles (returned by C, passed back into C — they're
# PyCapsule objects under the hood, but Python sees them as `object`)
# ─────────────────────────────────────────────────────────────────────

# Type aliases for documentation only — they all resolve to `object` so
# the type-checker doesn't reject passing them around.
Node = object
Chain = object
P2P = object
Block = object
Header = object
Transaction = object
Input = object
Output = object
Script = object
PaymentAddress = object
OutputPoint = object
Hash = bytes  # always 32 bytes


# ─────────────────────────────────────────────────────────────────────
# Front-door API: config + node lifecycle
# ─────────────────────────────────────────────────────────────────────

def config_settings_default(network: int) -> Settings: ...
def config_node_settings_default(network: int) -> NodeSettings: ...
def config_database_settings_default(network: int) -> DatabaseSettings: ...
def config_network_settings_default(network: int) -> NetworkSettings: ...
def config_blockchain_settings_default(network: int) -> BlockchainSettings: ...
def config_settings_get_from_file(
    path: str,
) -> tuple[int, Settings | None, str | None]:
    """Load settings from a config file.

    Returns a 3-tuple `(ok, settings, error)`:
      * on success: `(1, settings, None)`
      * on failure: `(0, None, error_message)`
    """
    ...

def node_construct(settings: Settings, stdout_console: bool, /) -> Node: ...
def node_destruct(node: Node, /) -> None: ...
def node_chain(node: Node, /) -> Chain: ...
def node_p2p(node: Node, /) -> P2P: ...
def node_signal_stop(node: Node, /) -> None: ...
def node_print_thread_id() -> None: ...
def node_init_run_and_wait_for_signal(
    node: Node,
    start_modules: int,
    callback: Callable[[int], Any],
    /,
) -> None: ...

def p2p_address_count(p2p: P2P, /) -> int: ...
def p2p_close(p2p: P2P, /) -> None: ...
def p2p_stop(p2p: P2P, /) -> None: ...
def p2p_stopped(p2p: P2P, /) -> bool: ...


# ─────────────────────────────────────────────────────────────────────
# Wallet — payment address triple
# ─────────────────────────────────────────────────────────────────────

def wallet_payment_address_construct_from_string(addr: str, /) -> PaymentAddress: ...
def wallet_payment_address_destruct(addr: PaymentAddress, /) -> None: ...
def wallet_payment_address_version(addr: PaymentAddress, /) -> int: ...
def wallet_payment_address_encoded_legacy(addr: PaymentAddress, /) -> str: ...

# NOTE: the `_cashaddr` and `_token` variants are only compiled in when
# the C extension was built with `KTH_CURRENCY=BCH` (the default). On
# BTC/LTC builds these functions are absent at runtime; calling them
# raises `AttributeError`. Until py-native ships per-currency stubs we
# expose them unconditionally — guard call sites with a feature check
# (`hasattr(kth_native, "wallet_payment_address_encoded_cashaddr")`)
# in code that needs to work across currencies.
def wallet_payment_address_encoded_cashaddr(
    addr: PaymentAddress, token_aware: bool, /
) -> str: ...
def wallet_payment_address_encoded_token(addr: PaymentAddress, /) -> str: ...


# ─────────────────────────────────────────────────────────────────────
# A handful of typed `chain_*` entry points commonly called by hand.
# ─────────────────────────────────────────────────────────────────────

def chain_fetch_last_height(
    chain: Chain, callback: Callable[[int, int], Any], /
) -> None: ...
def chain_fetch_block_by_height(
    chain: Chain, height: int, callback: Callable[[int, Block, int], Any], /
) -> None: ...
def chain_fetch_block_by_hash(
    chain: Chain, hash: Hash, callback: Callable[[int, Block, int], Any], /
) -> None: ...
def chain_fetch_block_height(
    chain: Chain, hash: Hash, callback: Callable[[int, int], Any], /
) -> None: ...
def chain_fetch_transaction(
    chain: Chain,
    hash: Hash,
    require_confirmed: bool,
    callback: Callable[[int, Transaction, int, int], Any],
    /,
) -> None: ...

def chain_block_destruct(block: Block, /) -> None: ...
def chain_block_hash(block: Block, /) -> Hash: ...
def chain_block_header(block: Block, /) -> Header: ...
def chain_block_transactions(block: Block, /) -> object: ...
def chain_block_serialized_size(block: Block, /) -> int: ...
def chain_block_factory_from_data(data: bytes, /) -> Block: ...

def chain_transaction_destruct(tx: Transaction, /) -> None: ...
def chain_transaction_hash(tx: Transaction, /) -> bytearray: ...
def chain_transaction_locktime(tx: Transaction, /) -> int: ...
def chain_transaction_factory_from_data(data: bytes, /) -> Transaction: ...

def chain_header_destruct(header: Header, /) -> None: ...
def chain_header_hash(header: Header, /) -> Hash: ...
def chain_header_factory_from_data(data: bytes, /) -> Header: ...
def chain_header_to_data(header: Header, /) -> bytes: ...

def chain_script_destruct(script: Script, /) -> None: ...
def chain_script_construct_from_bytes(
    encoded: bytes, prefix: bool, /
) -> Script: ...

def chain_output_point_construct() -> OutputPoint: ...
def chain_output_point_construct_from_hash_index(
    hash: Hash, index: int, /
) -> OutputPoint: ...
def chain_output_point_destruct(p: OutputPoint, /) -> None: ...
def chain_output_point_hash(p: OutputPoint, /) -> bytes: ...
def chain_output_point_index(p: OutputPoint, /) -> int: ...


# ─────────────────────────────────────────────────────────────────────
# All remaining `chain_*` helpers — left as untyped catch-alls. Promote
# to a real signature above when a caller actually needs strict types.
# ─────────────────────────────────────────────────────────────────────

def chain_block_claim(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_fees(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_generate_merkle_root(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_distinct_transaction_set(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_extra_coinbases(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_internal_double_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_coinbase_claim(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_coinbase_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_is_valid_merkle_root(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_reward(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_signature_operations_bip16_active(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_block_total_inputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_header(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_nonce(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_reset(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_transaction_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_compact_block_transaction_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_block_header_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_block_header_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_compact_block_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_compact_block_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_history(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_merkle_block_by_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_merkle_block_by_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_fetch_transaction_position(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_bits(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_merkle(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_nonce(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_previous_block_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_set_bits(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_set_nonce(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_set_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_set_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_timestamp(*args: Any, **kwargs: Any) -> Any: ...
def chain_header_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_height(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_point(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_point_kind(*args: Any, **kwargs: Any) -> Any: ...
def chain_history_compact_value_or_previous_checksum(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_factory_from_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_previous_output(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_sequence(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_input_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_hash_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_header(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_reset(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_merkle_block_total_transaction_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_organize_block(*args: Any, **kwargs: Any) -> Any: ...
def chain_organize_transaction(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_factory_from_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_script(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_output_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_point_checksum(*args: Any, **kwargs: Any) -> Any: ...
def chain_point_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_point_index(*args: Any, **kwargs: Any) -> Any: ...
def chain_point_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_is_valid_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_satoshi_content_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_sigops(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_script_to_string(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_ephemeral_public_key_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_public_key_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_stealth_compact_transaction_hash(*args: Any, **kwargs: Any) -> Any: ...
def chain_subscribe_blockchain(*args: Any, **kwargs: Any) -> Any: ...
def chain_subscribe_transaction(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_construct(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_fees(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_inputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_double_spend(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_final(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_locktime_conflict(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_mature(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_missing_previous_outputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_null_non_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_oversized_coinbase(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_overspent(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_is_valid(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_construct_default(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_count(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_destruct(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_nth(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_list_push_back(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_outputs(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_serialized_size(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_set_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_signature_operations(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_signature_operations_bip16_active(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_to_data(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_total_input_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_total_output_value(*args: Any, **kwargs: Any) -> Any: ...
def chain_transaction_version(*args: Any, **kwargs: Any) -> Any: ...
def chain_unsubscribe(*args: Any, **kwargs: Any) -> Any: ...
def chain_validate_tx(*args: Any, **kwargs: Any) -> Any: ...
