#!/usr/bin/env bash
# NixOS wrapper around `scripts/build.sh`.
#
# On NixOS the system Python lives under `/nix/store/.../python3.13-env`,
# which is read-only, so `pip install -e .` against it fails with
# `[Errno 30] Read-only file system` when writing the editable-marker
# `.py` / `.pth` files into `site-packages`. The build also needs the
# nixpkgs gcc runtime on `LD_LIBRARY_PATH` because the pip-installed
# `cpuid_native` wheel (transitive dep of kthbuild → microarch) ships a
# manylinux `.so` that dlopens `libstdc++.so.6` from a system path that
# doesn't exist on NixOS.
#
# This wrapper:
#   1. Resolves the nixpkgs gcc runtime and prepends it to
#      LD_LIBRARY_PATH.
#   2. Creates (or reuses) a local `.venv` so the editable install has a
#      writable `site-packages` to target.
#   3. Scrubs the stale build / conan artifacts from the repo root so a
#      rebuild starts from a clean state (no stale headers from a
#      previous `kth/<ver>` under `kth/`, no cached `build/`, etc.).
#   4. Delegates to `scripts/build.sh` with all args forwarded verbatim
#      (e.g. `scripts/build-nix.sh 1.0.0 1`).
#   5. Runs the pytest suite against the just-installed extension,
#      unless `--no-tests` is passed as the first argument.
#
# Non-NixOS developers can keep using `scripts/build.sh` directly.

set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${HERE}/.." && pwd)"
BUILD_SH="${HERE}/build.sh"
VENV_DIR="${REPO_ROOT}/.venv"

if [[ ! -x "${BUILD_SH}" ]]; then
    echo "build-nix.sh: ${BUILD_SH} not found or not executable" >&2
    exit 1
fi

if ! command -v nix-build >/dev/null 2>&1; then
    echo "build-nix.sh: nix-build not on PATH; are you on NixOS?" >&2
    exit 1
fi

GCC_LIB="$(nix-build '<nixpkgs>' -A gcc.cc.lib --no-out-link)/lib"
export LD_LIBRARY_PATH="${GCC_LIB}${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

# Provision the venv on first run. Python 3 from PATH (Nix-provided) is
# fine — we only need a writable prefix, not a different interpreter.
if [[ ! -d "${VENV_DIR}" ]]; then
    echo "build-nix.sh: creating venv at ${VENV_DIR}" >&2
    python3 -m venv "${VENV_DIR}"
fi

# shellcheck disable=SC1091
source "${VENV_DIR}/bin/activate"

# `build.sh` runs `pip install -e .` (pip's isolated build env has
# `kthbuild` / `conan` as per pyproject.toml `build-system.requires`)
# AND then `python3 setup.py install` directly, which executes
# `conan install` from the *venv's* interpreter — not the isolated
# build env. Without `kthbuild` in the venv the recipe load blows up
# with `ModuleNotFoundError: No module named 'kthbuild'`. Install the
# conan tooling into the venv on first run so both invocations see
# it. `pip install` is a no-op when already satisfied, so subsequent
# runs are fast.
pip install --quiet --upgrade pip >/dev/null
# Always `--upgrade` — an existing `.venv` cached by a previous run may
# hold an older `conan` (1.x on some environments), but `pyproject.toml`
# declares `conan>=2.0` and `setup.py` shells out with Conan 2 semantics
# so the build silently diverges without this flag.
pip install --quiet --upgrade conan kthbuild setuptools wheel

# Clean stale build artefacts before the install. These are all
# regenerated by either conan or setuptools on every run, so wiping
# them up front avoids "stale kth/include headers from a previous
# version" and "setuptools cached a removed source file" classes of
# bugs. Keep the list conservative — nothing here is user-authored.
echo "build-nix.sh: cleaning stale build artefacts" >&2
rm -rf \
    "${REPO_ROOT}/build" \
    "${REPO_ROOT}/dist" \
    "${REPO_ROOT}/kth" \
    "${REPO_ROOT}/kth_py_native.egg-info"
find "${REPO_ROOT}" \
    -path "${VENV_DIR}" -prune -o \
    -type d -name '__pycache__' -print0 2>/dev/null |
    xargs -0 -r rm -rf
rm -f \
    "${REPO_ROOT}/conanbuild.sh" \
    "${REPO_ROOT}/conanbuildenv"-*.sh \
    "${REPO_ROOT}/conanbuildinfo.cmake" \
    "${REPO_ROOT}/conaninfo.txt" \
    "${REPO_ROOT}/conan_imports_manifest.txt" \
    "${REPO_ROOT}/conanrun.sh" \
    "${REPO_ROOT}/conanrunenv"-*.sh \
    "${REPO_ROOT}/deactivate_conanbuild.sh" \
    "${REPO_ROOT}/deactivate_conanrun.sh" \
    "${REPO_ROOT}/debug.log" \
    "${REPO_ROOT}/error.log"

# Parse optional `--no-tests` flag (must be the first arg). Everything
# after it — or the full argv if the flag is absent — is forwarded to
# `build.sh`.
RUN_TESTS=1
if [[ ${1:-} == "--no-tests" ]]; then
    RUN_TESTS=0
    shift
fi

"${BUILD_SH}" "$@"

if (( RUN_TESTS )); then
    # Lightweight extra — pytest lives behind the optional `[test]` extra
    # in pyproject.toml, but the `dev` / `test` extras aren't installed
    # by `pip install -e .` on their own. Install just what we need, in
    # the venv, and run the suite.
    pip install --quiet pytest
    echo "build-nix.sh: running pytest against ${REPO_ROOT}/tests" >&2
    cd "${REPO_ROOT}"
    exec pytest tests
fi
